"""SQLAlchemy Metadata and Session object"""

__all__ = ['engine', 'meta', 'Session', 'engines', 'Sessions', 'nextSession']

# SQLAlchemy database engine.  Updated by model.init_model().
engine = None
engines = []

# SQLAlchemy session manager.  Updated by model.init_model().
Session = None
Sessions = []
nextSession = 0

# Global metadata. If you have multiple databases with overlapping table names, you'll need a metadata for each database.


## File autogenerated by genmodel.py
from sqlalchemy import MetaData, Table, Column, ForeignKey, Boolean, Integer, BigInteger, SmallInteger, String, DateTime, Enum, BLOB, UniqueConstraint, func

meta = MetaData()

from flx.model.mongocry import key as k

Key = k.Key()

def encryptKey():
    #
    #  Should only be run once during boot strapping.
    #
    #  Comment out to prevent it from running by accident.
    #
    if False:
        from flx.lib import kms

        key = Key.getKey()
        eekey = kms.encryptKey(key)
        Key.putKey(eekey)

def getKey():
    from flx.lib import kms

    eekey = Key.getKey()
    return kms.getKey(eekey)

if Key.isEncryptionEnabled:
    key = getKey()
else:
    key = None

from flx.lib import aes
from sqlalchemy.types import TypeDecorator

class EncryptedValue(TypeDecorator):
    impl = String

    def process_bind_param(self, value, dialect):
        if key:
            return aes.encrypt(value, key)
        return value

    def process_result_value(self, value, dialect):
        if key:
            return aes.decrypt(value, key)
        return value

########## Reviewed Tables ##########

ArtifactDraft = Table('ArtifactDraft', meta,
  Column('id', Integer(),  primary_key=True, autoincrement=True, nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id', name='ArtifactDraft_fk_creator', onupdate='cascade', ondelete='cascade'),  nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id', name='ArtifactDraft_fk_type', onupdate='cascade', ondelete='cascade'),  nullable=False),
  Column('handle', String(),  nullable=False),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', name='ArtifactDraft_fk_revision', onupdate='cascade', ondelete='cascade'), nullable=True),
  Column('draft', BLOB(), nullable=False),
  Column('isCompressed', Boolean(), nullable=False, default=False),
  Column('created', DateTime(timezone=True), nullable=False, default=func.now()),
  Column('updated', DateTime(timezone=True), nullable=False, default=func.now(),  onupdate=func.now()),

  UniqueConstraint('creatorID', 'artifactTypeID', 'handle', name='ArtifactDraft_uk_creator-type-handle'),
  UniqueConstraint('creatorID', 'artifactRevisionID', name='ArtifactDraft_uk_creator-revision')
)

#####################################

Artifacts = Table('Artifacts', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('ancestorID', Integer(), ForeignKey('ArtifactRevisions.id')),
  Column('licenseID', Integer(), ForeignKey('Licenses.id')),
  Column('languageID', SmallInteger(), ForeignKey('Languages.id'), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
)

ArtifactHandles = Table('ArtifactHandles', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), primary_key=True, nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), primary_key=True, nullable=False),
)

ArtifactAuthors = Table('ArtifactAuthors', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('roleID', Integer(), ForeignKey('MemberRoles.id'), primary_key=True, nullable=False),
  Column('sequence', Integer()),
)

ArtifactAttributers = Table('ArtifactAttributers', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('roleID', Integer(), ForeignKey('MemberRoles.id'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('givenName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('middleName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('surname', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True),
  Column('prefix', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('suffix', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('email', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('url', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('institution', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True),
)

ArtifactContributionType = Table('ArtifactContributionType', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('typeName', Enum('original', 'derived', 'modified'), nullable=False),
)

FeaturedArtifacts = Table('FeaturedArtifacts', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('listOrder', SmallInteger(), nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

TypedFeaturedArtifacts = Table('TypedFeaturedArtifacts', meta,
  Column('id', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('listOrder', SmallInteger(), nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('typeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

Licenses = Table('Licenses', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

MemberRoles = Table('MemberRoles', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('is_admin_role', Boolean(), nullable=False),
)

Subjects = Table('Subjects', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

ArtifactRevisionRelations = Table('ArtifactRevisionRelations', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('hasArtifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('sequence', Integer()),
)

ResourceRevisions = Table('ResourceRevisions', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id', ondelete='cascade'),  nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('hash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('filesize', Integer(), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('publishTime', DateTime(timezone=False),  nullable=True),
)

RevisionAndResources = Table('RevisionAndResources', meta,
  Column('revID', Integer(),  ForeignKey('ArtifactRevisions.id'), primary_key=True, nullable=False),
  Column('id', Integer(),  ForeignKey('ResourceRevisions.id'), primary_key=True, nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id'),  nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('hash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('filesize', Integer(), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('publishTime', DateTime(timezone=False),  nullable=True),
)

Languages = Table('Languages', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('code', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

Resources = Table('Resources', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('resourceTypeID', Integer(), ForeignKey('ResourceTypes.id'),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('authors', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('license', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('refHash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('checksum', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('satelliteUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('ownerID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('languageID', SmallInteger(), ForeignKey('Languages.id')),
  Column('isExternal', SmallInteger()),
  Column('isAttachment', SmallInteger()),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

InlineResourceDocuments = Table('InlineResourceDocuments', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id'),  nullable=False),
  Column('documentID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
)

ActionTypes = Table('ActionTypes', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

StandardBoards = Table('StandardBoards', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('longname', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('countryID', Integer(), ForeignKey('Countries.id'),  nullable=False),
  Column('sequence', Integer(), nullable=True),
)

Grades = Table('Grades', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

Groups = Table('Groups', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('parentID', Integer(), ForeignKey('Groups.id'),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('isActive', SmallInteger(), default=True),
  Column('accessCode', String(length=5, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), unique=True, nullable=True),
  Column('groupScope', Enum('open', 'closed', 'protected'), nullable=False, default="closed"),
  Column('origin', Enum('ck-12', 'lms'), nullable=False, default='ck-12'),
  Column('resourceRevisionID', Integer(), ForeignKey('ResourceRevisions.id'), primary_key=False, nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('groupType', Enum('study', 'class', 'public-forum', 'editing'), nullable=False, default="study"),
  Column('isVisible', Boolean(), nullable=False, default=True),
)

GroupMemberStates = Table('GroupMemberStates', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

GroupHasMembers = Table('GroupHasMembers', meta,
  Column('groupID', Integer(),  ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('roleID', Integer(), ForeignKey('MemberRoles.id'), primary_key=True,  nullable=False),
  Column('statusID', SmallInteger(), ForeignKey('GroupMemberStates.id'), nullable=False, default=2),
  Column('memberEmail', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('joinTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('disableNotification', SmallInteger(), nullable=False, default=0),
)

GroupHasArtifacts = Table('GroupHasArtifacts', meta,
  Column('groupID', Integer(),  ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
)

GroupActivities = Table('GroupActivities', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('groupID', Integer(),  ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'), primary_key=True,  nullable=False),
  Column('activityType', Enum('create','join','share','leave','assign','unassign','assignment-delete','change-due-date','assignment-edit','ph-question','ph-comment','ph-answer')),
  Column('objectType', Enum('artifact','artifactRevision','resource','resourceRevision','notification','member','group','peerhelp_post'), nullable=True),
  Column('objectID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('activityData', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ForumMetadata = Table('ForumMetadata', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('groupID', Integer(), ForeignKey('Groups.id', ondelete='cascade'), primary_key=False, nullable=False),
  Column('taggedWithRoleID', Integer(),  ForeignKey('MemberRoles.id'), primary_key=False, nullable=True),
  Column('tagLine', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  UniqueConstraint('groupID', 'taggedWithRoleID', name='ForumMetadata_uk_groupID-roleID'),
)

MemberViewedGroupActivities = Table('MemberViewedGroupActivities', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('groupID', Integer(), ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('activityID', Integer(), ForeignKey('GroupActivities.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('viewedTime', DateTime(timezone=False),  nullable=False),
)

SharedArtifacts = Table('SharedArtifacts', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('roleID', Integer(),  ForeignKey('MemberRoles.id'), primary_key=True, nullable=False),
)

Members = Table('Members', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('stateID', Integer(), nullable=False),
  Column('login', EncryptedValue(255),  nullable=False),
  Column('email', EncryptedValue(255),  nullable=False),
  Column('givenName', EncryptedValue(255),  nullable=False),
  Column('surname', EncryptedValue(255),  nullable=False),
  Column('defaultLogin', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('timezone', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False, default="US/Pacific"),
)

MemberAccessTimes = Table('MemberAccessTimes', meta,
  #Column('id', Integer(), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('objectType', Enum('group', 'inapp_notifications'), primary_key=True, nullable=True),
  Column('objectID', Integer(), primary_key=True, nullable=False),
  Column('accessTime', DateTime(timezone=False),  nullable=False),
)

MemberAuthApprovals = Table('MemberAuthApprovals', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('domain', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('approve', Integer(), nullable=False),
)

MemberViewedArtifacts = Table('MemberViewedArtifacts', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('lastViewTime', DateTime(timezone=False),  nullable=False),
)

BlockedMembers = Table('BlockedMembers', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('objectType', Enum('group','artifact'), nullable=False),
  Column('subObjectType', Enum('public-forum', 'study', 'class', 'book', 'concept'), nullable=True),
  Column('objectID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('blockedBy', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('reason', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('creationTime', DateTime(timezone=False), nullable=False),
)

CampaignMembers = Table('CampaignMembers', meta,
  Column('campaignID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
)

TypedMemberViewedArtifacts = Table('TypedMemberViewedArtifacts', meta,
  Column('memberID', Integer(), ForeignKey('Members.id'), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('typeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('lastViewTime', DateTime(timezone=False),  nullable=False),
)

TypedArtifactFavorites = Table('TypedArtifactFavorites', meta,
  Column('memberID', Integer(), ForeignKey('Members.id'), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('typeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

ArtifactRevisions = Table('ArtifactRevisions', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'),  nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('comment', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('messageToUsers', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('downloads', Integer()),
  Column('favorites', Integer()),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('publishTime', DateTime(timezone=False)),
)

ArtifactTypes = Table('ArtifactTypes', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('extensionType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('modality', Boolean()),
)

Countries = Table('Countries', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('code2Letter', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('code3Letter', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('codeNumeric', SmallInteger()),
  Column('image', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

Standards = Table('Standards', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('standardBoardID', SmallInteger(), ForeignKey('StandardBoards.id'),  nullable=False),
  Column('subjectID', SmallInteger(), ForeignKey('Subjects.id'),  nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

StandardHasGrades = Table('StandardHasGrades', meta,
  Column('standardID', Integer(), ForeignKey('Standards.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('gradeID', Integer(), ForeignKey('Grades.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

BrowseTermTypes = Table('BrowseTermTypes', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

BrowseTerms = Table('BrowseTerms', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('termTypeID', SmallInteger(), ForeignKey('BrowseTermTypes.id'),  nullable=False),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id')),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
)

TagTerms = Table('TagTerms', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

SearchTerms = Table('SearchTerms', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

PseudoDomainHandleSequencer = Table('PseudoDomainHandleSequencer', meta,
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('sequence', Integer(), nullable=False),
)

BrowseTermHasSynonyms = Table('BrowseTermHasSynonyms', meta,
    Column('termID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True),
    Column('synonymTermID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True),
)

DomainNeighbors = Table('DomainNeighbors', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('requiredDomainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
)

EncodedIDNeighbors = Table('EncodedIDNeighbors', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('requiredDomainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('requiredEncodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

ArtifactRevisionHasStandards = Table('ArtifactRevisionHasStandards', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

ArtifactRevisionHasResources = Table('ArtifactRevisionHasResources', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('resourceRevisionID', Integer(), ForeignKey('ResourceRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

ResourceTypes = Table('ResourceTypes', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('versionable', Integer()),
  Column('streamable', Integer()),
)

AccessControls = Table('AccessControls', meta,
  Column('roleID', Integer(),  ForeignKey('MemberRoles.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('actionTypeID', SmallInteger(),  ForeignKey('ActionTypes.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('isAllowed', SmallInteger()),
)

ArtifactHasBrowseTerms = Table('ArtifactHasBrowseTerms', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('browseTermID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

ArtifactHasTagTerms = Table('ArtifactHasTagTerms', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('tagTermID', Integer(), ForeignKey('TagTerms.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

ArtifactHasSearchTerms = Table('ArtifactHasSearchTerms', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('searchTermID', Integer(), ForeignKey('SearchTerms.id', ondelete='cascade'),  primary_key=True, nullable=False),
)

StopWords = Table('StopWords', meta,
  Column('word', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('Artifacts.id'),  primary_key=True, nullable=False),
)

ArtifactRevisionFavorites = Table('ArtifactRevisionFavorites', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ArtifactFeedbacks = Table('ArtifactFeedbacks', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('score', SmallInteger()),
  Column('type', Enum('rating','vote', 'relevance', 'creativity', 'clarity', 'impactful'), primary_key=True, nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('isApproved', Boolean(), nullable=False, default=0),
  Column('notAbuse', Boolean(), nullable=False, default=0),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ArtifactFeedbackReviews = Table('ArtifactFeedbackReviews', meta,
  Column('id', Integer(), primary_key=True,  nullable=False),
  Column('artifactID', Integer(), ForeignKey('ArtifactFeedbacks.artifactID'), nullable=False),
  Column('memberID', Integer(), ForeignKey('ArtifactFeedbacks.memberID'), nullable=False),
  Column('type', Enum('rating','vote'), ForeignKey('ArtifactFeedbacks.type'), nullable=False),
  Column('reviewersMemberID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('reviewComment', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('notAbuse', Boolean(), nullable=False, default=0),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updationTime', DateTime(timezone=False),  nullable=False),
)

ArtifactFeedbackAbuseReports = Table('ArtifactFeedbackAbuseReports', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('reporterMemberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ArtifactFeedbackReviewAbuseReports = Table('ArtifactFeedbackReviewAbuseReports', meta,
  Column('artifactFeedbackReviewID', Integer(), ForeignKey('ArtifactFeedbackReviews.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('reporterMemberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ArtifactFeedbackHelpful = Table('ArtifactFeedbackHelpful', meta,
  Column('artifactID', Integer(), ForeignKey('ArtifactFeedbacks.artifactID', ondelete='cascade'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('ArtifactFeedbacks.memberID', ondelete='cascade'), primary_key=True, nullable=False),
  Column('type', Enum('rating','vote'), ForeignKey('ArtifactFeedbacks.type'), primary_key=True, nullable=False),
  Column('reviewersMemberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('isHelpful', Boolean(), nullable=False),
)

ArtifactFeedbackAndCount = Table('ArtifactFeedbackAndCount', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('score', SmallInteger(), primary_key=True, nullable=False),
  Column('type', Enum('rating','vote', 'relevance', 'creativity', 'clarity', 'impactful'), primary_key=True, nullable=False),
  Column('count', BigInteger()),
)

ArtifactFeedbackHelpfulAndCount = Table('ArtifactFeedbackHelpfulAndCount', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True,  nullable=False),
  Column('type', Enum('rating','vote')),
  Column('isHelpful', SmallInteger(), primary_key=True, nullable=False),
  Column('count', BigInteger()),
)

PublishRequests = Table('PublishRequests', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('requestTime', DateTime(timezone=False),  nullable=False),
)

ArtifactsAndBrowseTerms = Table('ArtifactsAndBrowseTerms', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('browseTermID', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('termTypeID', SmallInteger(), nullable=False),
  Column('parentID', Integer()),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
)

ArtifactsAndTagTerms = Table('ArtifactsAndTagTerms', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('tagTermID', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
)

ArtifactsAndSearchTerms = Table('ArtifactsAndSearchTerms', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('searchTermID', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
)

ArtifactAndChildren = Table('ArtifactAndChildren', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('childID', Integer(), primary_key=True, nullable=False),
  Column('sequence', Integer()),
)

RevisionAndStandards = Table('RevisionAndStandards', meta,
  Column('rid', Integer(), ForeignKey('ArtifactRevisionHasStandards.artifactRevisionID'), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('ArtifactRevisionHasStandards.artifactID'), primary_key=False, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id'), primary_key=True,  nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('boardID', Integer(), ForeignKey('StandardBoards.id'), primary_key=False, nullable=False),
  Column('boardName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('countryID', Integer(), ForeignKey('Countries.id'), nullable=False),
  Column('subjectID', Integer(), ForeignKey('Subjects.id'), nullable=False),
  Column('subjectName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

StandardAndGrades = Table('StandardAndGrades', meta,
  Column('sid', Integer(), ForeignKey('Standards.id'), primary_key=True, nullable=False),
  Column('id', SmallInteger(), ForeignKey('Grades.id'), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

WorkDirectory = Table('WorkDirectory', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('relativePath', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('toPurge', SmallInteger(), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

MathImage = Table('MathImage', meta,
  Column('hash', String(length=20, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('eqnType', Enum('block', 'inline')),
  Column('target', Integer(), nullable=False),
  Column('expression', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('resourceUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

BrowseTermCandidates = Table('BrowseTermCandidates', meta,
  Column('categoryID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('rangeStart', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('rangeEnd', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('sequence', Integer(), nullable=False),
)

BrowseTermCandidateRanges = Table('BrowseTermCandidateRanges', meta,
  Column('categoryID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('rangeStart', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('rangeEnd', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
)

Tasks = Table('Tasks', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('taskID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('status', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'), primary_key=False, nullable=True),
  Column('message', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('userdata', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('artifactKey', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('hostname', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('started', DateTime(timezone=False),  nullable=False),
  Column('updated', DateTime(timezone=False),  nullable=False),
)

EmbeddedObjectProviders = Table("EmbeddedObjectProviders", meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('domain', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('blacklisted', SmallInteger(), primary_key=False, nullable=False),
  Column('needsApi', SmallInteger(), primary_key=False, nullable=False),
  Column('created', DateTime(timezone=False), nullable=False),
  Column('updated', DateTime(timezone=False), nullable=False),
)

AbuseReasons = Table('AbuseReasons', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
)

AbuseReports = Table("AbuseReports", meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('resourceRevisionID', Integer(), ForeignKey('ResourceRevisions.id'), primary_key=False, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), primary_key=False, nullable=True),
  Column('reason', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('reasonID', Integer(), ForeignKey('AbuseReasons.id'), primary_key=False, nullable=True),
  Column('remark', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('status', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('reporterID', Integer(), ForeignKey('Members.id'), primary_key=False, nullable=True),
  Column('reviewerID', Integer(), ForeignKey('Members.id'), primary_key=False, nullable=True),
  Column('imageUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('userAgent', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('created', DateTime(timezone=False), nullable=False),
  Column('updated', DateTime(timezone=False), nullable=False),
)

EmbeddedObjects = Table("EmbeddedObjects", meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('providerID', Integer(), ForeignKey('EmbeddedObjectProviders.id'), primary_key=False, nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id'), primary_key=False, nullable=True),
  Column('type', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('caption', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('code', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('thumbnail', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('blacklisted', SmallInteger(), primary_key=False, nullable=False),
  Column('hash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('width', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('height', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('created', DateTime(timezone=False), nullable=False),
  Column('updated', DateTime(timezone=False), nullable=False),
)

DomainUrls = Table('DomainUrls', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('url', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('iconUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

EmbeddedObjectCache = Table('EmbeddedObjectCache', meta,
  Column('urlHash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('cache', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
)

ArtifactAndResources = Table('ArtifactAndResources', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), primary_key=True, nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), primary_key=False, nullable=False),
  Column('id', Integer(),  ForeignKey('Resources.id'), primary_key=True, nullable=False),
  Column('resourceTypeID', Integer(), ForeignKey('ResourceTypes.id'),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('authors', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('license', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('refHash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('languageID', SmallInteger(), ForeignKey('Languages.id')),
  Column('isExternal', SmallInteger()),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('checksum', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('satelliteUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
 )

DownloadStats = Table('DownloadStats', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('downloadType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('count', Integer(), nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
)

EventTypes = Table('EventTypes', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
)

Events = Table('Events', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('eventTypeID', Integer(), ForeignKey('EventTypes.id'), nullable=False),
  Column('objectID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('subObjectID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('eventData', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('ownerID', Integer(), ForeignKey('Members.id'), nullable=True),
  Column('subscriberID', Integer(), ForeignKey('Members.id'), nullable=True),
  Column('created', DateTime(timezone=False), nullable=False),
)

NotificationRules = Table('NotificationRules', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
)

Notifications = Table('Notifications', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('eventTypeID', Integer(), ForeignKey('EventTypes.id'), nullable=False),
  Column('objectID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('type', Enum('email', 'text', 'web'),  nullable=False),
  Column('ruleID', Integer(), ForeignKey('NotificationRules.id'), nullable=True),
  Column('address', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('subscriberID', Integer(), ForeignKey('Members.id'), nullable=True),
  Column('groupID', Integer(), ForeignKey('Groups.id'), nullable=True),
  Column('copyTo', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('frequency', Enum('instant', 'once', '6hours', '12hours', 'daily', 'weekly', 'ondemand', 'off'),  nullable=False),
  Column('lastSent', DateTime(timezone=False), nullable=True),
  Column('created', DateTime(timezone=False), nullable=False),
  Column('updated', DateTime(timezone=False), nullable=False),
)

EflexUserDetails = Table('EflexUserDetails', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('email', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('isSuccessful', SmallInteger()),
  Column('errorCount', Integer()),
  Column('isRegistered', SmallInteger()),
  Column('isBlacklisted', SmallInteger()),
)

EflexUserRequests = Table('EflexUserRequests', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('eflexUserDetailID', Integer(), ForeignKey('EflexUserDetails.id'),  nullable=False),
  Column('requester', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('emailBody', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('status', SmallInteger()),
  Column('artifactID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
)

MemberLibraryObjects = Table('MemberLibraryObjects', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('objectID', Integer(), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('parentID', Integer(), nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=False),
  Column('created', DateTime(timezone=False), nullable=False),
)

MemberLibraryArtifactRevisions = Table('MemberLibraryArtifactRevisions', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
)

MemberLibraryArtifactRevisionsAndBrowseTerms = Table('MemberLibraryArtifactRevisionsAndBrowseTerms', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
  Column('browseTermID', Integer(), ForeignKey('BrowseTerms.id'), nullable=False),
  Column('termTypeID', Integer(), ForeignKey('BrowseTermTypes.id'), nullable=False),
  Column('term', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
)

MemberLibraryResourceRevisions = Table('MemberLibraryResourceRevisions', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('resourceRevisionID', Integer(), ForeignKey('ResourceRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id'), nullable=False),
  Column('resourceTypeID', Integer(), ForeignKey('ResourceTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'), nullable=False),
)

MemberLabels = Table('MemberLabels', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=True),
  Column('label', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('systemLabel', SmallInteger(), nullable=False),
  Column('sticky', SmallInteger(), nullable=False, default=False),
  Column('created', DateTime(timezone=False), nullable=False),
)

MemberLibraryObjectHasLabels = Table('MemberLibraryObjectHasLabels', meta,
  Column('labelID', Integer(), ForeignKey('MemberLabels.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('libraryObjectID', Integer(), ForeignKey('MemberLibraryObjects.id', ondelete='cascade'), primary_key=True, nullable=False),
)

MemberLibraryArtifactRevisionHasLabels = Table('MemberLibraryArtifactRevisionHasLabels', meta,
  Column('labelID', Integer(), ForeignKey('MemberLabels.id', ondelete='cascade'), primary_key=True, nullable=True),
  Column('libraryObjectID', Integer(), ForeignKey('MemberLibraryArtifactRevisions.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('labelName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('systemLabel', SmallInteger(), nullable=True),
  Column('labelOwnerID', Integer(), nullable=True),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('login', EncryptedValue(255),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
)

MemberLibraryArtifactRevisionHasLabelsAndBrowseTerms = Table('MemberLibraryArtifactRevisionHasLabelsAndBrowseTerms', meta,
  Column('labelID', Integer(), ForeignKey('MemberLabels.id', ondelete='cascade'), primary_key=True, nullable=True),
  Column('libraryObjectID', Integer(), ForeignKey('MemberLibraryArtifactRevisions.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('labelName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('systemLabel', SmallInteger(), nullable=True),
  Column('labelOwnerID', Integer(), nullable=True),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('login', EncryptedValue(255),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
  Column('browseTermID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('termTypeID', Integer(), ForeignKey('BrowseTermTypes.id'), nullable=False),
  Column('term', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
)

MemberLibraryResourceRevisionHasLabels = Table('MemberLibraryResourceRevisionHasLabels', meta,
  Column('labelID', Integer(), ForeignKey('MemberLabels.id', ondelete='cascade'), primary_key=True, nullable=True),
  Column('libraryObjectID', Integer(), ForeignKey('MemberLibraryResourceRevisions.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=True),
  Column('labelName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('systemLabel', SmallInteger(), nullable=True),
  Column('resourceRevisionID', Integer(), ForeignKey('ResourceRevisions.id'), nullable=False),
  Column('objectType', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('added', DateTime(timezone=False), nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id'), nullable=False),
  Column('resourceTypeID', Integer(), ForeignKey('ResourceTypes.id'), nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'), nullable=False),
)

ContentRevisions = Table('ContentRevisions', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('log', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
)

Contents = Table('Contents', meta,
  Column('resourceURI', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('Resources.uri', ondelete='cascade'), primary_key=True, nullable=False),
  Column('ownerID', Integer(), ForeignKey('Resources.ownerID'), primary_key=True, nullable=False),
  Column('contentRevisionID', Integer(), ForeignKey('ContentRevisions.id'), primary_key=True, nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('contents', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('checksum', String(length=256, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('compressed', SmallInteger(), nullable=False),
)

ArtifactsStandardsGradesAndBrowseTerms = Table('ArtifactsStandardsGradesAndBrowseTerms', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), primary_key=True, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id'), primary_key=True, nullable=False),
  Column('termID', Integer(), ForeignKey('BrowseTerms.id'), primary_key=True, nullable=False),
  Column('gradeID', Integer(), ForeignKey('Grades.id'), primary_key=True, nullable=False),
  Column('boardID', Integer(), ForeignKey('StandardBoards.id'), nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('boardName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('boardLongName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('sequence', Integer(), nullable=True),
  Column('countryID', Integer(), ForeignKey('Countries.id'), nullable=False),
  Column('termTypeID', Integer(), ForeignKey('BrowseTermTypes.id'), nullable=False),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('termName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('gradeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

ArtifactAndRevisions = Table('ArtifactAndRevisions', meta,
  Column('id', Integer(), ForeignKey('Artifacts.id'), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('ancestorID', Integer(), ForeignKey('ArtifactRevisions.id')),
  Column('licenseID', Integer(), ForeignKey('Licenses.id')),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('typeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), primary_key=True, nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('downloads', Integer()),
  Column('favorites', Integer()),
  Column('revCreationTime', DateTime(timezone=False),  nullable=False),
  Column('publishTime', DateTime(timezone=False)),
  Column('login', EncryptedValue(255),  nullable=False),
)

From1xBookMembers = Table('From1xBookMembers', meta,
  Column('memberID', Integer(), ForeignKey('Members.id'), primary_key=True,  nullable=False),
  Column('memberID1x', Integer(), nullable=False),
  Column('taskID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('Tasks.taskID'), nullable=True),
  Column('started', DateTime(timezone=False),  nullable=True),
  Column('migrated', DateTime(timezone=False),  nullable=True),
  Column('status', Enum('Not Started', 'In Progress', 'Done', 'Acknowledged', 'Declined'), nullable=False),
)

From1xBookMemberInfo = Table('From1xBookMemberInfo', meta,
  Column('memberID', Integer(), ForeignKey('Members.id'), primary_key=True,  nullable=False),
  Column('memberID1x', Integer(), nullable=False),
  Column('taskID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('Tasks.taskID'), nullable=True),
  Column('started', DateTime(timezone=False),  nullable=True),
  Column('migrated', DateTime(timezone=False),  nullable=True),
  Column('status', Enum('Not Started', 'In Progress', 'Done', 'Acknowledged', 'Declined'), nullable=False),
  Column('email', EncryptedValue(255),  nullable=False),
)

From1xBooks = Table('From1xBooks', meta,
  Column('fid', Integer(), ForeignKey('Members.id'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
)

From1xChapters = Table('From1xChapters', meta,
  Column('cid', Integer(), ForeignKey('Members.id'), primary_key=True,  nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), nullable=False),
)

DomainHasStandards = Table('DomainHasStandards', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id', ondelete='cascade'), primary_key=True, nullable=False),
)

ArtifactDomainAndStandards = Table('ArtifactDomainAndStandards', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), primary_key=True, nullable=False),
  Column('browseTermID', Integer(), ForeignKey('BrowseTerms.id'), primary_key=True, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id'), primary_key=True, nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('termName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('boardID', Integer(), ForeignKey('StandardBoards.id'), nullable=False),
  Column('boardName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('countryID', Integer(), ForeignKey('Countries.id'), nullable=False),
  Column('subjectID', Integer(), ForeignKey('Subjects.id'), nullable=False),
  Column('subjectName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

ArtifactDomainsStandardsGradesAndBrowseTerms = Table('ArtifactDomainsStandardsGradesAndBrowseTerms', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id'), primary_key=True, nullable=False),
  Column('standardID', Integer(), ForeignKey('Standards.id'), primary_key=True, nullable=False),
  Column('termID', Integer(), ForeignKey('BrowseTerms.id'), primary_key=True, nullable=False),
  Column('termTypeID', Integer(), ForeignKey('BrowseTermTypes.id'), primary_key=False, nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('subject', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id'), primary_key=False, nullable=True),
  Column('termName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('boardID', Integer(), ForeignKey('StandardBoards.id'), nullable=False),
  Column('boardName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('boardLongName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('sequence', Integer(), nullable=True),
  Column('countryID', Integer(), ForeignKey('Countries.id'), nullable=False),
  Column('gradeID', Integer(), ForeignKey('Grades.id'), nullable=False),
  Column('gradeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

PublishedArtifacts = Table('PublishedArtifacts', meta,
  Column('id', Integer(),  ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('ancestorID', Integer(), ForeignKey('ArtifactRevisions.id')),
  Column('licenseID', Integer(), ForeignKey('Licenses.id')),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('artifactRevisionID', Integer(),  ForeignKey('ArtifactRevisions.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('publishTime', DateTime(timezone=False)),
)

RelatedArtifacts = Table('RelatedArtifacts', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('sequence', Integer(), primary_key=False, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('conceptCollectionHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, default='', nullable=False),
  Column('collectionCreatorID', Integer(), primary_key=True, default=0, nullable=False),
)

RelatedArtifactsBackup = Table('RelatedArtifactsBackup', meta,
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('sequence', Integer(), primary_key=True, nullable=False),
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('conceptCollectionHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, default='', nullable=False),
  Column('collectionCreatorID', Integer(), primary_key=True, default=0, nullable=False),
)
 
RelatedArtifactsAndLevels = Table('RelatedArtifactsAndLevels', meta,
  Column('id', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('artifactTypeID', Integer(), ForeignKey('ArtifactTypes.id'), nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('ancestorID', Integer(), ForeignKey('ArtifactRevisions.id')),
  Column('licenseID', Integer(), ForeignKey('Licenses.id')),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id'), nullable=False),
  Column('publishTime', DateTime(timezone=False), nullable=True),
  Column('level', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('domainID', Integer(), ForeignKey('BrowseTerms.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('conceptCollectionHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, default='', nullable=False),
  Column('collectionCreatorID', Integer(), primary_key=True, default=0, nullable=False),
  Column('domainTerm', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('domainHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('domainEID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('parentID', Integer(), ForeignKey('BrowseTerms.id'), nullable=True),
  Column('sequence', Integer(), primary_key=True, nullable=False),
)

Vocabularies = Table('Vocabularies', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('term', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('definition', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('languageID', SmallInteger(), ForeignKey('Languages.id')),
)

ArtifactHasVocabularies = Table('ArtifactHasVocabularies', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('vocabularyID', Integer(), ForeignKey('Vocabularies.id', ondelete='cascade'),  primary_key=True, nullable=False),
  Column('sequence', Integer(), nullable=False),
)

ArtifactsAndVocabularies = Table('ArtifactsAndVocabularies', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id'),  nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('vocabularyID', Integer(), ForeignKey('Vocabularies.id'),  primary_key=True, nullable=False),
  Column('term', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('definition', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('sequence', Integer(), nullable=False),
  Column('languageCode', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('languageName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

RwaVotes = Table('RwaVotes', meta,
  Column('id', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
  Column('creatorID', Integer(), ForeignKey('Members.id'), nullable=True),
  Column('votes', Integer(), nullable=True),
)

MemberHasGrades = Table('MemberHasGrades', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('gradeID', SmallInteger(), ForeignKey('Grades.id', ondelete='cascade'), primary_key=True, nullable=False)
)

MemberHasSubjects = Table('MemberHasSubjects', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('subjectID', SmallInteger(), ForeignKey('Subjects.id', ondelete='cascade'), primary_key=True, nullable=False)
)

GroupHasGrades = Table('GroupHasGrades', meta,
  Column('groupID', Integer(), ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('gradeID', SmallInteger(), ForeignKey('Grades.id', ondelete='cascade'), primary_key=True, nullable=False)
)

GroupHasSubjects = Table('GroupHasSubjects', meta,
  Column('groupID', Integer(), ForeignKey('Groups.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('subjectID', SmallInteger(), ForeignKey('Subjects.id', ondelete='cascade'), primary_key=True, nullable=False)
)

StandardsBoardsSubjectsAndGrades = Table('StandardsBoardsSubjectsAndGrades', meta,
  Column('id', Integer(), ForeignKey('Standards.id'), primary_key=True, nullable=False),
  Column('section', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('standardBoardID', Integer(), ForeignKey('StandardBoards.id'), nullable=False),
  Column('boardName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('boardLongName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('sequence', Integer(), nullable=True),
  Column('countryID', Integer(), ForeignKey('Countries.id'), nullable=False),
  Column('subjectID', Integer(), ForeignKey('Subjects.id'), nullable=False),
  Column('subjectName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('gradeID', Integer(), ForeignKey('Grades.id'), nullable=False),
  Column('gradeName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
)

Assignments = Table('Assignments', meta,
  Column('assignmentID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('groupID', Integer(), ForeignKey('Groups.id'), nullable=True),
  Column('assignmentType', Enum('assignment', 'self-assignment', 'self-study'), nullable=False, default="assignment"),
  Column('origin', Enum('ck-12', 'lms'), nullable=False, default="ck-12"),
  Column('due', DateTime(timezone=False),  nullable=True),
)

MemberStudyTrackItemStatus = Table('MemberStudyTrackItemStatus', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('assignmentID', Integer(), ForeignKey('Assignments.assignmentID', ondelete='cascade'), primary_key=True, nullable=False),
  Column('studyTrackItemID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('status', Enum('completed', 'skipped', 'incomplete'), nullable=False, default="incomplete"),
  Column('score', Integer(), nullable=True),
  Column('lastAccess', DateTime(timezone=False),  nullable=True),
)

LMSProviders = Table('LMSProviders', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
)

LMSProviderApps = Table('LMSProviderApps', meta,
  Column('providerID', Integer(), ForeignKey('LMSProviders.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('appID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('appName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('policy', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
)

LMSProviderGroups = Table('LMSProviderGroups', meta,
  Column('appID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('LMSProviderApps.appID'), primary_key=True, nullable=False),
  Column('providerGroupID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('groupID', Integer(), ForeignKey('Groups.id'), nullable=True),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
)

LMSProviderGroupMembers = Table('LMSProviderGroupMembers', meta,
  Column('providerID', Integer(), ForeignKey('LMSProviders.id'), primary_key=True, nullable=False),
  Column('providerGroupID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('LMSProviderGroups.providerGroupID', ondelete='cascade'), primary_key=True, nullable=False),
  Column('providerMemberID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('memberID', Integer(), ForeignKey('Members.id'), nullable=True),
)

LMSProviderAssignments = Table('LMSProviderAssignments', meta,
  Column('providerID', Integer(), ForeignKey('LMSProviders.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('providerAssignmentID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('assignmentID', Integer(), ForeignKey('Assignments.assignmentID'), nullable=True),
  Column('isValid', Boolean(), nullable=False, default=True)
)

LMSProviderAssignmentScores = Table('LMSProviderAssignmentScores', meta,
  Column('providerID', Integer(), ForeignKey('LMSProviders.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('providerGroupID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('providerMemberID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('providerAssignmentID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('testScoreID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('score', Integer(), nullable=False),
  Column('status', Enum('private', 'reported'), nullable=False, default="private"),
)

Retrolation = Table('Retrolation', meta,
  Column('domainEID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), ForeignKey('BrowseTerms.encodedID'), primary_key=True, nullable=False),
  Column('sectionEID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False)
)

Courses = Table('Courses', meta,
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('shortName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('title', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('creationTime', DateTime(timezone=False), nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False)
)

EmailReceivers = Table('EmailReceivers', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('email', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('status', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=False)
)

EmailSenders = Table('EmailSenders', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('email', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False)
)

EmailSharings = Table('EmailSharings', meta,
  Column('senderID', Integer(), ForeignKey('EmailSenders.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('receiverID', Integer(), ForeignKey('EmailReceivers.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('emailType', Enum('share','summer','feedback','app_link'), primary_key=True, nullable=False, default='share'),
  Column('count', Integer(), nullable=False)
)

BookEditingAssignments = Table('BookEditingAssignments', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('bookID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), nullable=False),
  Column('assigneeID', Integer(), ForeignKey('Members.id', ondelete='cascade'), nullable=False),
  Column('groupID', Integer(), ForeignKey('Groups.id', ondelete='cascade'), nullable=False),
  Column('artifactTypeID', SmallInteger(), ForeignKey('ArtifactTypes.id', ondelete='cascade'),  nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)


BookEditingDrafts = Table('BookEditingDrafts', meta,
  Column('artifactRevisionID', Integer(), ForeignKey('ArtifactRevisions.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('assigneeID', Integer(), ForeignKey('Members.id', ondelete='cascade'), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

BookFinalizations = Table('BookFinalizations', meta,
  Column('bookID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('taskID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
  Column('total', Integer(), nullable=False),
  Column('completed', Integer(), nullable=False),
  Column('creationTime', DateTime(timezone=False), nullable=False),
  Column('updateTime', DateTime(timezone=False), nullable=False),
)

BookFinalizationLocks = Table('BookFinalizationLocks', meta,
  Column('artifactID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('bookID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), nullable=False),
  Column('message', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), nullable=True),
)

ConceptMapFeedbacks = Table('ConceptMapFeedbacks', meta,
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('reviewer', Integer(), ForeignKey('Members.id', ondelete='cascade'), nullable=True),
  Column('visitorID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('encodedID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('suggestion', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, nullable=False),
  Column('status', Enum('reviewing', 'accepted', 'rejected'), nullable=False),
  Column('comments', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('notes', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
)

StudyTrackItemContexts = Table('StudyTrackItemContexts', meta,
  Column('studyTrackID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('studyTrackItemID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('contextUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), default='', nullable=False),
  Column('conceptCollectionHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, default='', nullable=False),
  Column('collectionCreatorID', Integer(), primary_key=True, default=0, nullable=False),
)

TeacherStudentRelations = Table('TeacherStudentRelations', meta,
  Column('studentID', Integer(), ForeignKey('Members.id'), primary_key=True, nullable=True),
  Column('teacherID', Integer(), ForeignKey('Members.id'), primary_key=True, nullable=True),
  Column('creationTime', DateTime(timezone=False), nullable=False),
)

#Archive table for Member Study Track Item Status
ArchivedMemberStudyTrackItemStatus = Table('ArchivedMemberStudyTrackItemStatus', meta,
  Column('artifactTypeID', SmallInteger(), nullable=False),
  Column('assignmentName', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('assignmentDescription', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('assignmentCreatorID', Integer(), nullable=False),
  Column('assignmentID', Integer(), ForeignKey('Assignments.assignmentID', ondelete='cascade'), primary_key=True, nullable=False),
  Column('groupID', Integer(), nullable=True),
  Column('assignmentType', Enum('assignment', 'self-assignment', 'self-study'), nullable=False, default="assignment"),
  Column('origin', Enum('ck-12', 'lms'), nullable=False, default="ck-12"),
  Column('due', DateTime(timezone=False), nullable=True),
  Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('studyTrackItemID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
  Column('status', Enum('completed', 'skipped', 'incomplete'), nullable=False, default="incomplete"),
  Column('score', Integer(), nullable=True),
  Column('lastAccess', DateTime(timezone=False), nullable=True),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('updateTime', DateTime(timezone=False),  nullable=False),
)

MigratedConcepts = Table('MigratedConcepts', meta,
    Column('originalEID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  primary_key=True, nullable=False),
    Column('newEID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  primary_key=True, nullable=False),
)

MemberSelfStudyItemStatus = Table('MemberSelfStudyItemStatus', meta,
    Column('domainID', Integer(), ForeignKey('Artifacts.id', ondelete='cascade'), primary_key=True, nullable=False),
    Column('memberID', Integer(), ForeignKey('Members.id', ondelete='cascade'), primary_key=True, nullable=False),
    Column('conceptCollectionHandle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=True, default='', nullable=False),
    Column('collectionCreatorID', Integer(), ForeignKey('Members.id'), primary_key=True, default=0, nullable=False),
    Column('status', Enum('completed', 'skipped', 'incomplete'), nullable=False, default="incomplete"),
    Column('score', Integer(), nullable=True),
    Column('lastAccess', DateTime(timezone=False),  nullable=True),
    Column('contextUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), default=None, nullable=True),
)
