"""SQLAlchemy Metadata and Session object"""

__all__ = ['engine', 'meta', 'Session', 'engines', 'Sessions', 'nextSession']

# SQLAlchemy database engine.  Updated by model.init_model().
engine = None
engines = []

# SQLAlchemy session manager.  Updated by model.init_model().
Session = None
Sessions = []
nextSession = 0

# Global metadata. If you have multiple databases with overlapping table names, you'll need a metadata for each database.


## File autogenerated by genmodel.py
from sqlalchemy import MetaData, Table, Column, ForeignKey, Integer, SmallInteger, String, DateTime

meta = MetaData()

Languages = Table('Languages', meta,
  Column('id', SmallInteger(),  primary_key=True, nullable=False),
  Column('code', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
)

Members = Table('Members', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('stateID', Integer(), nullable=False),
  Column('login', String(255),  nullable=False),
  Column('email', String(255),  nullable=False),
  Column('givenName', String(255),  nullable=False),
  Column('surname', String(255),  nullable=False),
  Column('defaultLogin', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('timezone', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False, default="US/Pacific"),
)

Resources = Table('Resources', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('resourceTypeID', Integer(), ForeignKey('ResourceTypes.id'),  nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('handle', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('authors', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('license', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('uri', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('refHash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('checksum', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('satelliteUrl', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('ownerID', Integer(), ForeignKey('Members.id'),  nullable=False),
  Column('languageID', SmallInteger(), ForeignKey('Languages.id')),
  Column('isExternal', SmallInteger()),
  Column('isAttachment', SmallInteger()),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
)

ResourceRevisions = Table('ResourceRevisions', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('resourceID', Integer(), ForeignKey('Resources.id', ondelete='cascade'),  nullable=False),
  Column('revision', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('hash', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=True),
  Column('filesize', Integer(), nullable=False),
  Column('creationTime', DateTime(timezone=False),  nullable=False),
  Column('publishTime', DateTime(timezone=False),  nullable=True),
)

ResourceTypes = Table('ResourceTypes', meta,
  Column('id', Integer(),  primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False),  nullable=False),
  Column('description', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False)),
  Column('versionable', Integer()),
  Column('streamable', Integer()),
)

Tasks = Table('Tasks', meta,
  Column('id', Integer(), primary_key=True, nullable=False),
  Column('name', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('taskID', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('status', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=False),
  Column('ownerID', Integer(), ForeignKey('Members.id'), primary_key=False, nullable=True),
  Column('message', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('userdata', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('artifactKey', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('hostname', String(length=None, convert_unicode=False, unicode_error=None, _warn_on_bytestring=False), primary_key=False, nullable=True),
  Column('started', DateTime(timezone=False),  nullable=False),
  Column('updated', DateTime(timezone=False),  nullable=False),
)
