USE flx2img;

--
--  Drop some foreign keys
--
ALTER TABLE `Artifacts` DROP FOREIGN KEY `Artifacts_ibfk_3`;
ALTER TABLE `ArtifactRevisions` DROP FOREIGN KEY `ArtifactRevisions_ibfk_1`;
ALTER TABLE `Standards` DROP FOREIGN KEY `Standards_ibfk_1`;
ALTER TABLE `BrowseTerms` DROP FOREIGN KEY `BrowseTerms_ibfk_1`;
ALTER TABLE `Events` DROP FOREIGN KEY `Events_ibfk_2`;
ALTER TABLE `Notifications` DROP FOREIGN KEY `Notifications2_ibfk_1`;
ALTER TABLE `Notifications` DROP FOREIGN KEY `Notifications2_ibfk_3`;
ALTER TABLE `Notifications` DROP FOREIGN KEY `Notifications2_ibfk_4`;
ALTER TABLE `MemberRoles` DROP FOREIGN KEY `MemberRoles_ibfk_1`;

--
--  Views
--
DROP VIEW IF EXISTS `AliasEncodedIDs`;
DROP VIEW IF EXISTS `ArtifactAndChildren`;
DROP VIEW IF EXISTS `ArtifactAndResources`;
DROP VIEW IF EXISTS `ArtifactAndRevisions`;
DROP VIEW IF EXISTS `ArtifactDomainAndStandards`;
DROP VIEW IF EXISTS `ArtifactDomainsStandardsGradesAndBrowseTerms`;
DROP VIEW IF EXISTS `ArtifactFeedbackAndCount`;
DROP VIEW IF EXISTS `ArtifactPopularities`;
DROP VIEW IF EXISTS `ArtifactRevisionPopularities`;
DROP VIEW IF EXISTS `ArtifactsAndBrowseTerms`;
DROP VIEW IF EXISTS `ArtifactsAndSearchTerms`;
DROP VIEW IF EXISTS `ArtifactsAndTagTerms`;
DROP VIEW IF EXISTS `ArtifactsAndVocabularies`;
DROP VIEW IF EXISTS `ArtifactsStandardsGradesAndBrowseTerms`;
DROP VIEW IF EXISTS `EncodedIDNeighbors`;
DROP VIEW IF EXISTS `From1xBookMemberInfo`;
DROP VIEW IF EXISTS `MemberLibraryArtifactRevisionHasLabels`;
DROP VIEW IF EXISTS `MemberLibraryArtifactRevisionHasLabelsAndBrowseTerms`;
DROP VIEW IF EXISTS `MemberLibraryArtifactRevisions`;
DROP VIEW IF EXISTS `MemberLibraryArtifactRevisionsAndBrowseTerms`;
DROP VIEW IF EXISTS `MemberLibraryResourceRevisionHasLabels`;
DROP VIEW IF EXISTS `MemberLibraryResourceRevisions`;
DROP VIEW IF EXISTS `PublishedArtifacts`;
DROP VIEW IF EXISTS `RelatedArtifactsAndLevels`;
DROP VIEW IF EXISTS `RevisionAndResources`;
DROP VIEW IF EXISTS `RevisionAndStandards`;
DROP VIEW IF EXISTS `RwaVotes`;
DROP VIEW IF EXISTS `StandardAndGrades`;
DROP VIEW IF EXISTS `StandardsBoardsSubjectsAndGrades`;
DROP VIEW IF EXISTS `TypedArtifactFavorites`;
DROP VIEW IF EXISTS `TypedFeaturedArtifacts`;
DROP VIEW IF EXISTS `TypedMemberViewedArtifacts`;

--
--  Tables
--
DROP TABLE IF EXISTS `AbuseReports`;
DROP TABLE IF EXISTS `AbuseReasons`;
DROP TABLE IF EXISTS `AccessControls`;
DROP TABLE IF EXISTS `ArtifactAttributers`;
DROP TABLE IF EXISTS `ArtifactAuthors`;
DROP TABLE IF EXISTS `ArtifactContributionType`;
DROP TABLE IF EXISTS `ArtifactDraft`;
DROP TABLE IF EXISTS `ArtifactFeedbackAbuseReports`;
DROP TABLE IF EXISTS `ArtifactFeedbackHelpful`;
DROP TABLE IF EXISTS `ArtifactFeedbackReviewAbuseReports`;
DROP TABLE IF EXISTS `ArtifactHandles`;
DROP TABLE IF EXISTS `ArtifactHasBrowseTerms`;
DROP TABLE IF EXISTS `ArtifactHasSearchTerms`;
DROP TABLE IF EXISTS `ArtifactHasTagTerms`;
DROP TABLE IF EXISTS `ArtifactHasVocabularies`;
DROP TABLE IF EXISTS `ArtifactRevisionFavorites`;
DROP TABLE IF EXISTS `ArtifactRevisionHasResources`;
DROP TABLE IF EXISTS `ArtifactRevisionHasStandards`;
DROP TABLE IF EXISTS `ArtifactRevisionRelations`;
DROP TABLE IF EXISTS `BlockedMembers`;
DROP TABLE IF EXISTS `BrowseTermCandidates`;
DROP TABLE IF EXISTS `BrowseTermHasSynonyms`;
DROP TABLE IF EXISTS `CampaignMembers`;
DROP TABLE IF EXISTS `ConceptMapFeedbacks`;
DROP TABLE IF EXISTS `DomainHasStandards`;
DROP TABLE IF EXISTS `DomainNeighbors`;
DROP TABLE IF EXISTS `DomainUrls`;
DROP TABLE IF EXISTS `EflexUserRequests`;
DROP TABLE IF EXISTS `EmailSharings`;
DROP TABLE IF EXISTS `EmbeddedObjects`;
DROP TABLE IF EXISTS `Events`;
DROP TABLE IF EXISTS `FeaturedArtifacts`;
DROP TABLE IF EXISTS `From1xBooks`;
DROP TABLE IF EXISTS `From1xChapters`;
DROP TABLE IF EXISTS `GroupHasArtifacts`;
DROP TABLE IF EXISTS `GroupHasGrades`;
DROP TABLE IF EXISTS `GroupHasMembers`;
DROP TABLE IF EXISTS `GroupHasSubjects`;
DROP TABLE IF EXISTS `InteractiveEntries`;
DROP TABLE IF EXISTS `LMSProviderAssignmentScores`;
DROP TABLE IF EXISTS `LMSProviderAssignments`;
DROP TABLE IF EXISTS `LMSProviderGroupMembers`;
DROP TABLE IF EXISTS `LMSProviderGroups`;
DROP TABLE IF EXISTS `MemberHasGrades`;
DROP TABLE IF EXISTS `MemberHasSubjects`;
DROP TABLE IF EXISTS `MemberLibraryObjectHasLabels`;
DROP TABLE IF EXISTS `MemberStudyTrackItemStatus`;
DROP TABLE IF EXISTS `MemberStudyTrackItemStatusNew`;
DROP TABLE IF EXISTS `MemberViewedArtifacts`;
DROP TABLE IF EXISTS `MemberViewedGroupActivities`;
DROP TABLE IF EXISTS `Notifications_old`;
DROP TABLE IF EXISTS `OAuthTokens`;
DROP TABLE IF EXISTS `Overlays`;
DROP TABLE IF EXISTS `PublishRequests`;
DROP TABLE IF EXISTS `RelatedArtifacts`;
DROP TABLE IF EXISTS `Retrolation`;
DROP TABLE IF EXISTS `SharedArtifacts`;
DROP TABLE IF EXISTS `StandardBoards`;
DROP TABLE IF EXISTS `StandardHasGrades`;
DROP TABLE IF EXISTS `StudyTrackItemContexts`;
DROP TABLE IF EXISTS `TeacherStudentRelations`;

DROP TABLE IF EXISTS `Assignments`;
DROP TABLE IF EXISTS `GroupActivities`;
DROP TABLE IF EXISTS `LMSProviderApps`;
DROP TABLE IF EXISTS `MemberLabels`;
DROP TABLE IF EXISTS `MemberLibraryObjects`;
DROP TABLE IF EXISTS `OAuthClients`;
DROP TABLE IF EXISTS `Standards`;

DROP TABLE IF EXISTS `ArtifactFeedbackReviews`;
DROP TABLE IF EXISTS `ArtifactFeedbacks`;
DROP TABLE IF EXISTS `Artifacts`;
DROP TABLE IF EXISTS `ArtifactRevisions`;
DROP TABLE IF EXISTS `ArtifactTypes`;
DROP TABLE IF EXISTS `ActionTypes`;
DROP TABLE IF EXISTS `BrowseTermTypes`;
DROP TABLE IF EXISTS `BrowseTerms`;
DROP TABLE IF EXISTS `Contents`;
DROP TABLE IF EXISTS `ContentRevisions`;
DROP TABLE IF EXISTS `Courses`;
DROP TABLE IF EXISTS `Countries`;
DROP TABLE IF EXISTS `DownloadStats`;
DROP TABLE IF EXISTS `EflexUserDetails`;
DROP TABLE IF EXISTS `EmailReceivers`;
DROP TABLE IF EXISTS `EmailSenders`;
DROP TABLE IF EXISTS `EmbeddedObjectCache`;
DROP TABLE IF EXISTS `EmbeddedObjectProviders`;
DROP TABLE IF EXISTS `EventTypes`;
DROP TABLE IF EXISTS `From1xBookMembers`;
DROP TABLE IF EXISTS `GetRealJudgesWeight`;
DROP TABLE IF EXISTS `Grades`;
DROP TABLE IF EXISTS `Groups`;
DROP TABLE IF EXISTS `GroupMemberStates`;
DROP TABLE IF EXISTS `MemberRoles`;
DROP TABLE IF EXISTS `InlineResourceDocuments`;
DROP TABLE IF EXISTS `InteractiveEntryTypes`;
DROP TABLE IF EXISTS `LMSProviders`;
DROP TABLE IF EXISTS `Licenses`;
DROP TABLE IF EXISTS `MathImage`;
DROP TABLE IF EXISTS `MemberAccessTimes`;
DROP TABLE IF EXISTS `MemberAuthApprovals`;
DROP TABLE IF EXISTS `MemberAuthTypes`;
DROP TABLE IF EXISTS `NotificationRules`;
DROP TABLE IF EXISTS `Notifications`;
DROP TABLE IF EXISTS `PseudoDomainHandleSequencer`;
DROP TABLE IF EXISTS `RelatedArtifactsBackup`;
DROP TABLE IF EXISTS `SearchTerms`;
DROP TABLE IF EXISTS `TagTerms`;
DROP TABLE IF EXISTS `Vocabularies`;
DROP TABLE IF EXISTS `StopWords`;
DROP TABLE IF EXISTS `Subjects`;
DROP TABLE IF EXISTS `USStates`;
DROP TABLE IF EXISTS `WorkDirectory`;
