create table `InlineResourceDocuments` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The autogenerated id for this table', 
    `resourceID` int(11) NOT NULL COMMENT 'Resource ID', 
    `documentID` varchar(128) NOT NULL COMMENT 'Unique ID of box viewer document for the resource.',
    `creationTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'The creation time.',
    `updateTime` timestamp NULL DEFAULT NULL COMMENT 'The updated time.',
    PRIMARY KEY (`id`), 
    CONSTRAINT `InlineResourceDocuments_ibfk_1` FOREIGN KEY (`resourceID`) REFERENCES `Resources` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=innoDB DEFAULT CHARSET=utf8 COMMENT='Resource boxviewer document details';
