INSERT INTO `Members` (`id`, `stateID`, `gender`, `login`, `email`, `givenName`, `surname`, `suffix`, `title`) VALUES
(4, 2, NULL, 'ck12eflex', 'eflex@ck12.org', 'CK12', 'eFlex', '', '');
 
INSERT INTO `MemberExtData` (`memberID`, `authTypeID`, `token`) VALUES
(4, 1, 'sha256:df6289b1b201df269309cde293e94604b0da7a12aa4ca182b037c0b1fca150f1');

INSERT INTO `MemberRoles` (`id`, `name`, `description`) VALUES
(13, 'member', 'Member');
 
INSERT INTO `GroupHasMembers` (`groupID`, `memberID`, `roleID`) VALUES
(1, 4, 13);

DROP TABLE IF EXISTS `EflexUserDetails`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
create table `EflexUserDetails` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The autogenerated id for this table', 
    `memberID` int(11) NOT NULL COMMENT 'Member ID', 
    `email` varchar(75) NOT NULL COMMENT 'Email ID of the requester', 
    `isSuccessful` tinyint(1) DEFAULT 0, 
    `errorCount` smallint(2) DEFAULT 0, 
    `isRegistered` tinyint(1) DEFAULT 0, 
    `isBlacklisted` tinyint(1) DEFAULT 0, 
    PRIMARY KEY (`id`), 
    CONSTRAINT `EflexUserDetails_ibfk_1` FOREIGN KEY (`memberID`) REFERENCES `Members` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=innoDB DEFAULT CHARSET=utf8 COMMENT='Eflex User details';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `EflexUserRequests`
--

DROP TABLE IF EXISTS `EflexUserRequests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
create table `EflexUserRequests` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The autogenerated id for this table', 
    `EflexUserDetailID` int(11) NOT NULL COMMENT 'Eflex user detail ID', 
    `requester` varchar(75) NOT NULL, 
    `title` varchar(250), 
    `emailBody` mediumtext, 
    `status` smallint(1), 
    PRIMARY KEY (`id`), 
    CONSTRAINT `EflexUserRequests_ibfk_1` FOREIGN KEY (`EflexUserDetailID`) REFERENCES `EflexUserDetails` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=innoDB DEFAULT CHARSET=utf8 COMMENT='Eflex User Requests';
/*!40101 SET character_set_client = @saved_cs_client */;


