SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.100', @subjectID, @branchID, 'Introduction to Software Testing--NEW--', 'Introduction-to-Software-Testing--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.110', @subjectID, @branchID, 'Testing is Exploration: TEST THIS!--NEW--', 'Testing-is-Exploration-TEST-THIS--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.120', @subjectID, @branchID, 'What is Software Testing?--NEW--', 'What-is-Software-Testing--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.130', @subjectID, @branchID, 'Testers Ask Questions--NEW--', 'Testers-Ask-Questions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.140', @subjectID, @branchID, 'What Do Testers Find?--NEW--', 'What-Do-Testers-Find--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.150', @subjectID, @branchID, 'Understanding Programming: TEST THIS!--NEW--', 'Understanding-Programming-TEST-THIS--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.160', @subjectID, @branchID, 'What Does Quality Assurance Mean?--NEW--', 'What-Does-Quality-Assurance-Mean--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.170', @subjectID, @branchID, 'Attributes of Good Testers--NEW--', 'Attributes-of-Good-Testers--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.180', @subjectID, @branchID, 'Personal Perspectives on Software Testing--NEW--', 'Personal-Perspectives-on-Software-Testing--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.181', @subjectID, @branchID, 'If I Could Write a Letter to Me: Michael Larsen--NEW--', 'If-I-Could-Write-a-Letter-to-Me-Michael-Larsen--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.180' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.182', @subjectID, @branchID, 'If I Could Write a Letter To Me: Ben Simo--NEW--', 'If-I-Could-Write-a-Letter-To-Me-Ben-Simo--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.180' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'ENG.TST.183', @subjectID, @branchID, 'If I Could Write a Letter to Me: Timothy Western--NEW--', 'If-I-Could-Write-a-Letter-to-Me-Timothy-Western--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'ENG.TST.180' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'ENG';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'TST';
UPDATE `ConceptNodes` SET `name`=CONCAT(`name`,'--OLD--') WHERE (`name` NOT LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `name`=SUBSTR(`name`,1,LENGTH(`name`)-7) WHERE (`name` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `handle`=SUBSTR(`handle`,1,LENGTH(`handle`)-7) WHERE (`handle` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.110');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.100';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.110';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.120');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.110';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.120';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.130');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.120';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.130';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.140');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.130';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.140';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.150');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.140';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.150';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.160');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.150';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.160';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.170');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.160';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.170';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.180');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.170';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.180';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.181');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.180';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.181';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.182');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.181';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.182';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.183');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'ENG.TST.182';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'ENG.TST.183';
