SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.100', @subjectID, @branchID, 'Units of Measurement--NEW--', 'Units-of-Measurement--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.110', @subjectID, @branchID, 'Metric System--NEW--', 'Metric-System--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.111', @subjectID, @branchID, 'Equivalent Metric Units of Capacity--NEW--', 'Equivalent-Metric-Units-of-Capacity--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.112', @subjectID, @branchID, 'Equivalent Metric Units of Length--NEW--', 'Equivalent-Metric-Units-of-Length--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.113', @subjectID, @branchID, 'Equivalent Metric Units of Mass--NEW--', 'Equivalent-Metric-Units-of-Mass--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.114', @subjectID, @branchID, 'Metric Unit Length Conversions--NEW--', 'Metric-Unit-Length-Conversions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.115', @subjectID, @branchID, 'Appropriate Metric Units of Mass or Capacity--NEW--', 'Appropriate-Metric-Units-of-Mass-or-Capacity--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.116', @subjectID, @branchID, 'Appropriate Decimal Units for Metric Measurement--NEW--', 'Appropriate-Decimal-Units-for-Metric-Measurement--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.118', @subjectID, @branchID, 'Metric Length Comparison--NEW--', 'Metric-Length-Comparison--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.119', @subjectID, @branchID, 'Conversions of Length, Mass, Capacity in Metric Units--NEW--', 'Conversions-of-Length-Mass-Capacity-in-Metric-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.110' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.119.1', @subjectID, @branchID, 'Comparison of Metric Measurements--NEW--', 'Comparison-of-Metric-Measurements--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.119' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.120', @subjectID, @branchID, 'Standard Units--NEW--', 'Standard-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.121', @subjectID, @branchID, 'Customary Units of Length--NEW--', 'Customary-Units-of-Length--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.120' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.130', @subjectID, @branchID, 'Nonstandard Units--NEW--', 'Nonstandard-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.140', @subjectID, @branchID, 'Reading Maps, Legends/Scale--NEW--', 'Reading-Maps-Legends-Scale--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.142', @subjectID, @branchID, 'Distances or Dimensions Given Scale Measurements--NEW--', 'Distances-or-Dimensions-Given-Scale-Measurements--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.140' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.144', @subjectID, @branchID, 'Scale Distances or Dimensions--NEW--', 'Scale-Distances-or-Dimensions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.140' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.144.1', @subjectID, @branchID, 'Unit Scale to Find Actual Dimensions--NEW--', 'Unit-Scale-to-Find-Actual-Dimensions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.144' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.144.2', @subjectID, @branchID, 'Scale Factor to Find Actual Dimensions--NEW--', 'Scale-Factor-to-Find-Actual-Dimensions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.144' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.150', @subjectID, @branchID, 'Appropriate Measurement Tools--NEW--', 'Appropriate-Measurement-Tools--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.151', @subjectID, @branchID, 'Appropriate Tools for Measurement of Squares and Rectangles--NEW--', 'Appropriate-Tools-for-Measurement-of-Squares-and-Rectangles--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.150' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.152', @subjectID, @branchID, 'Appropriate Tools for Metric Measurement--NEW--', 'Appropriate-Tools-for-Metric-Measurement--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.150' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.153', @subjectID, @branchID, 'Appropriate Tools for Customary Measurement--NEW--', 'Appropriate-Tools-for-Customary-Measurement--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.150' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.160', @subjectID, @branchID, 'Conversion of Customary Units of Measurement--NEW--', 'Conversion-of-Customary-Units-of-Measurement--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.162', @subjectID, @branchID, 'Conversion of Customary Units by Multiplying--NEW--', 'Conversion-of-Customary-Units-by-Multiplying--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.160' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.164', @subjectID, @branchID, 'Conversion of Customary Units by Dividing--NEW--', 'Conversion-of-Customary-Units-by-Dividing--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.160' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.165', @subjectID, @branchID, 'Conversion Using Unit Analysis--NEW--', 'Conversion-Using-Unit-Analysis--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.160' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.170', @subjectID, @branchID, 'Conversion of Systems of Measure--NEW--', 'Conversion-of-Systems-of-Measure--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.171', @subjectID, @branchID, 'Estimation of Conversion to Metric Units--NEW--', 'Estimation-of-Conversion-to-Metric-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.170' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.172', @subjectID, @branchID, 'Conversion Estimation between Systems of Measure--NEW--', 'Conversion-Estimation-between-Systems-of-Measure--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.170' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.180', @subjectID, @branchID, 'United States Customary Units--NEW--', 'United-States-Customary-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.200', @subjectID, @branchID, 'Linear Measure--NEW--', 'Linear-Measure--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.210', @subjectID, @branchID, 'Measurement of Distance--NEW--', 'Measurement-of-Distance--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.211', @subjectID, @branchID, 'Length Measurements to a Fraction of an Inch--NEW--', 'Length-Measurements-to-a-Fraction-of-an-Inch--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.210' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.220', @subjectID, @branchID, 'Measurement of Perimeter--NEW--', 'Measurement-of-Perimeter--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.230', @subjectID, @branchID, 'Measurement of Circumference--NEW--', 'Measurement-of-Circumference--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.300', @subjectID, @branchID, 'Measure of Area--NEW--', 'Measure-of-Area--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.310', @subjectID, @branchID, 'Measurement of Polygon Area--NEW--', 'Measurement-of-Polygon-Area--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.320', @subjectID, @branchID, 'Measurement of Circle Area--NEW--', 'Measurement-of-Circle-Area--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.330', @subjectID, @branchID, 'Measurement of Surface Area--NEW--', 'Measurement-of-Surface-Area--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.340', @subjectID, @branchID, 'Measurement of Nonstandard Shape Area--NEW--', 'Measurement-of-Nonstandard-Shape-Area--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.400', @subjectID, @branchID, 'Measure of Volume--NEW--', 'Measure-of-Volume--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.410', @subjectID, @branchID, 'Identification of Equivalent Customary Units of Capacity--NEW--', 'Identification-of-Equivalent-Customary-Units-of-Capacity--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.420', @subjectID, @branchID, 'Selection of Appropriate Weight or Capacity Units--NEW--', 'Selection-of-Appropriate-Weight-or-Capacity-Units--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.500', @subjectID, @branchID, 'Weight and Mass--NEW--', 'Weight-and-Mass--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.510', @subjectID, @branchID, 'Identification of Equivalent Customary Units of Weight--NEW--', 'Identification-of-Equivalent-Customary-Units-of-Weight--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.600', @subjectID, @branchID, 'Measure of Temperature--NEW--', 'Measure-of-Temperature--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.610', @subjectID, @branchID, 'Fahrenheit--NEW--', 'Fahrenheit--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.620', @subjectID, @branchID, 'Celsius--NEW--', 'Celsius--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.700', @subjectID, @branchID, 'Measure of Time--NEW--', 'Measure-of-Time--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.710', @subjectID, @branchID, 'Digital Clock--NEW--', 'Digital-Clock--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.720', @subjectID, @branchID, 'Clock with Hands--NEW--', 'Clock-with-Hands--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.730', @subjectID, @branchID, 'Addition and Subtraction with Time--NEW--', 'Addition-and-Subtraction-with-Time--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.740', @subjectID, @branchID, 'Elapsed Time--NEW--', 'Elapsed-Time--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.MEA.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.800', @subjectID, @branchID, 'Measure of Speed--NEW--', 'Measure-of-Speed--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.MEA.900', @subjectID, @branchID, 'Measure of Money--NEW--', 'Measure-of-Money--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'MEA';
UPDATE `ConceptNodes` SET `name`=CONCAT(`name`,'--OLD--') WHERE (`name` NOT LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `name`=SUBSTR(`name`,1,LENGTH(`name`)-7) WHERE (`name` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `handle`=SUBSTR(`handle`,1,LENGTH(`handle`)-7) WHERE (`handle` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.110');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.100';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.110';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.111');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.110';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.111';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.112');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.111';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.112';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.113');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.112';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.113';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.114');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.113';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.114';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.115');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.114';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.115';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.116');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.115';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.116';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.118');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.116';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.118';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.119');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.118';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.119';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.119.1');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.119';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.119.1';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.120');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.119.1';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.120';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.121');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.120';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.121';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.130');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.121';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.130';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.140');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.130';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.140';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.142');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.140';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.142';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.142';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.144';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144.1');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.144.1';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144.2');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144.1';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.144.2';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.150');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.144.2';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.150';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.151');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.150';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.151';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.152');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.151';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.152';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.153');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.152';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.153';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.160');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.153';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.160';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.162');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.160';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.162';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.164');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.162';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.164';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.165');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.164';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.165';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.170');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.165';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.170';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.171');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.170';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.171';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.172');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.171';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.172';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.180');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.172';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.180';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.200');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.180';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.200';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.210');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.200';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.210';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.211');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.210';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.211';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.220');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.211';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.220';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.230');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.220';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.230';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.300');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.230';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.300';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.310');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.300';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.310';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.320');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.310';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.320';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.330');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.320';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.330';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.340');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.330';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.340';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.400');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.340';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.400';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.410');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.400';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.410';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.420');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.410';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.420';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.500');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.420';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.500';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.510');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.500';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.510';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.600');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.510';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.600';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.610');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.600';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.610';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.620');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.610';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.620';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.700');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.620';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.700';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.710');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.700';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.710';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.720');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.710';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.720';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.730');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.720';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.730';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.740');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.730';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.740';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.800');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.740';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.800';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.900');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.MEA.800';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.MEA.900';
