SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.100', @subjectID, @branchID, 'Theoretical and Experimental Probability--NEW--', 'Theoretical-and-Experimental-Probability--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.101', @subjectID, @branchID, 'Definition of Probability--NEW--', 'Definition-of-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.110', @subjectID, @branchID, 'Measurement of Probability--NEW--', 'Measurement-of-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.120', @subjectID, @branchID, 'Empirical Probability--NEW--', 'Empirical-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.130', @subjectID, @branchID, 'Subjective Probability--NEW--', 'Subjective-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.140', @subjectID, @branchID, 'How Probability is Applied--NEW--', 'How-Probability-is-Applied--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.150', @subjectID, @branchID, 'Applications of Probability--NEW--', 'Applications-of-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.200', @subjectID, @branchID, 'Set Theory--NEW--', 'Set-Theory--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.210', @subjectID, @branchID, 'Sets--NEW--', 'Sets--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.220', @subjectID, @branchID, 'Venn Diagrams--NEW--', 'Venn-Diagrams--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.230', @subjectID, @branchID, 'Subsets--NEW--', 'Subsets--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.240', @subjectID, @branchID, 'Sample Spaces and Events--NEW--', 'Sample-Spaces-and-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.250', @subjectID, @branchID, 'Special Sets, Empty Set, Universal Set--NEW--', 'Special-Sets-Empty-Set-Universal-Set--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.260', @subjectID, @branchID, 'Operations with Sets--NEW--', 'Operations-with-Sets--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.270', @subjectID, @branchID, 'Properties of Set Operations--NEW--', 'Properties-of-Set-Operations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.300', @subjectID, @branchID, 'Counting Techniques--NEW--', 'Counting-Techniques--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.310', @subjectID, @branchID, 'Basic Counting Rules--NEW--', 'Basic-Counting-Rules--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.312', @subjectID, @branchID, 'Product Rule for Counting--NEW--', 'Product-Rule-for-Counting--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.310' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.314', @subjectID, @branchID, 'Sum Rule for Counting--NEW--', 'Sum-Rule-for-Counting--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.310' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.316', @subjectID, @branchID, 'Counting Rule to Calculate Probabilities--NEW--', 'Counting-Rule-to-Calculate-Probabilities--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.310' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.320', @subjectID, @branchID, 'Probability and Permutations--NEW--', 'Probability-and-Permutations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.321', @subjectID, @branchID, 'Permutations--NEW--', 'Permutations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.322', @subjectID, @branchID, 'Permutations and Combinations Compared--NEW--', 'Permutations-and-Combinations-Compared--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.324', @subjectID, @branchID, 'Permutation Problems--NEW--', 'Permutation-Problems--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.326', @subjectID, @branchID, 'Permutations with Repetition--NEW--', 'Permutations-with-Repetition--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.330', @subjectID, @branchID, 'Probability and Combinations--NEW--', 'Probability-and-Combinations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.332', @subjectID, @branchID, 'Combinations--NEW--', 'Combinations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.330' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.334', @subjectID, @branchID, 'Combination Problems--NEW--', 'Combination-Problems--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.330' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.340', @subjectID, @branchID, 'Partitions--NEW--', 'Partitions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.350', @subjectID, @branchID, 'Challenging Counting Problems--NEW--', 'Challenging-Counting-Problems--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.360', @subjectID, @branchID, 'Binomial Coefficients--NEW--', 'Binomial-Coefficients--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.370', @subjectID, @branchID, 'Pascal\'s Triangle--NEW--', 'Pascals-Triangle--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.400', @subjectID, @branchID, 'Probability of Compound Events--NEW--', 'Probability-of-Compound-Events--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.410', @subjectID, @branchID, 'Numerical Computations--NEW--', 'Numerical-Computations--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.420', @subjectID, @branchID, 'Tree Diagrams--NEW--', 'Tree-Diagrams--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.421', @subjectID, @branchID, 'Counting Events--NEW--', 'Counting-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.422', @subjectID, @branchID, 'Additive and Multiplicative Rules for Probability--NEW--', 'Additive-and-Multiplicative-Rules-for-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.423', @subjectID, @branchID, 'Complement Rule for Probability--NEW--', 'Complement-Rule-for-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.424', @subjectID, @branchID, 'Mutually Exclusive Events--NEW--', 'Mutually-Exclusive-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.425', @subjectID, @branchID, 'Mutually Inclusive Events--NEW--', 'Mutually-Inclusive-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.426', @subjectID, @branchID, 'Inequality for Probabilities--NEW--', 'Inequality-for-Probabilities--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.430', @subjectID, @branchID, 'Problems Using Dice--NEW--', 'Problems-Using-Dice--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.440', @subjectID, @branchID, 'Problems Involving Coin Tossing--NEW--', 'Problems-Involving-Coin-Tossing--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.450', @subjectID, @branchID, 'Problems Involving Cards--NEW--', 'Problems-Involving-Cards--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.460', @subjectID, @branchID, 'Geometric Probability--NEW--', 'Geometric-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.470', @subjectID, @branchID, 'Quality Control--NEW--', 'Quality-Control--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.480', @subjectID, @branchID, 'Birthday Problems--NEW--', 'Birthday-Problems--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.490', @subjectID, @branchID, 'Transmission Errors--NEW--', 'Transmission-Errors--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.500', @subjectID, @branchID, 'Conditional Probability and Independence--NEW--', 'Conditional-Probability-and-Independence--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.510', @subjectID, @branchID, 'Conditional Probability--NEW--', 'Conditional-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.520', @subjectID, @branchID, 'Multiplication Theorem for Conditional Probability--NEW--', 'Multiplication-Theorem-for-Conditional-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.530', @subjectID, @branchID, 'Switching Conditions--NEW--', 'Switching-Conditions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.540', @subjectID, @branchID, 'Partitions and the Law of Total Probability--NEW--', 'Partitions-and-the-Law-of-Total-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.550', @subjectID, @branchID, 'Bayes\' Formula for Conditional Probability--NEW--', 'Bayes-Formula-for-Conditional-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.560', @subjectID, @branchID, 'Independent Events--NEW--', 'Independent-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.561', @subjectID, @branchID, 'Probability of Independent Events--NEW--', 'Probability-of-Independent-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.560' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.570', @subjectID, @branchID, 'Dependent Events--NEW--', 'Dependent-Events--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.600', @subjectID, @branchID, 'Discrete and Continuous Random Variables--NEW--', 'Discrete-and-Continuous-Random-Variables--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.610', @subjectID, @branchID, 'Discrete Random Variables and Distribution--NEW--', 'Discrete-Random-Variables-and-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.612', @subjectID, @branchID, 'Discrete Random Variables--NEW--', 'Discrete-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.614', @subjectID, @branchID, 'Probability Distribution--NEW--', 'Probability-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.616', @subjectID, @branchID, 'Cumulative Distribution Function of a Random Variable--NEW--', 'Cumulative-Distribution-Function-of-a-Random-Variable--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.618', @subjectID, @branchID, 'Mean and Standard Deviation of Discrete Random Variables--NEW--', 'Mean-and-Standard-Deviation-of-Discrete-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.620', @subjectID, @branchID, 'Types of Distribution of Discrete Random Variables--NEW--', 'Types-of-Distribution-of-Discrete-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.621', @subjectID, @branchID, 'Sums and Differences of Independent Random Variables--NEW--', 'Sums-and-Differences-of-Independent-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.622', @subjectID, @branchID, 'Bernoulli Random Variable and the Binomial Distribution--NEW--', 'Bernoulli-Random-Variable-and-the-Binomial-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.622.1', @subjectID, @branchID, 'Binomial Distributions and Probability--NEW--', 'Binomial-Distributions-and-Probability--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.622.2', @subjectID, @branchID, 'Binompdf Function--NEW--', 'Binompdf-Function--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.622.3', @subjectID, @branchID, 'Binomcdf Function--NEW--', 'Binomcdf-Function--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.623', @subjectID, @branchID, 'Poisson Probability Distributions--NEW--', 'Poisson-Probability-Distributions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.624', @subjectID, @branchID, 'Geometric Probability Distributions--NEW--', 'Geometric-Probability-Distributions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.625', @subjectID, @branchID, 'Negative Binomial Distribution--NEW--', 'Negative-Binomial-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.626', @subjectID, @branchID, 'Hypergeometric Distribution--NEW--', 'Hypergeometric-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.627', @subjectID, @branchID, 'Multinomial Distributions--NEW--', 'Multinomial-Distributions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.630', @subjectID, @branchID, 'Continuous Random Variables--NEW--', 'Continuous-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.632', @subjectID, @branchID, 'Cumulative Distribution Function of a Continuous Random Variable--NEW--', 'Cumulative-Distribution-Function-of-a-Continuous-Random-Variable--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.630' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.640', @subjectID, @branchID, 'Types of Distribution of Continuous Random Variables--NEW--', 'Types-of-Distribution-of-Continuous-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.642', @subjectID, @branchID, 'Uniform Distribution--NEW--', 'Uniform-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.644', @subjectID, @branchID, 'Normal Distribution and Continuous Random Variables--NEW--', 'Normal-Distribution-and-Continuous-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.646', @subjectID, @branchID, 'Exponential Distributions--NEW--', 'Exponential-Distributions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.700', @subjectID, @branchID, 'Properties of the Normal Distribution--NEW--', 'Properties-of-the-Normal-Distribution--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.720', @subjectID, @branchID, 'Computing Probabilities for the Standard Normal Distribution--NEW--', 'Computing-Probabilities-for-the-Standard-Normal-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.730', @subjectID, @branchID, 'Empirical Rule--NEW--', 'Empirical-Rule--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.732', @subjectID, @branchID, 'Linear Interpolation of Normal Distributions--NEW--', 'Linear-Interpolation-of-Normal-Distributions--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.730' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.740', @subjectID, @branchID, 'Normal Approximation of the Binomial Distribution--NEW--', 'Normal-Approximation-of-the-Binomial-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.800', @subjectID, @branchID, 'Expected Value--NEW--', 'Expected-Value--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.820', @subjectID, @branchID, 'Expected Value for Discrete Random Variables--NEW--', 'Expected-Value-for-Discrete-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.840', @subjectID, @branchID, 'Expected Value for Continuous Random Variables--NEW--', 'Expected-Value-for-Continuous-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.860', @subjectID, @branchID, 'Expectation of a Multiple or Sum of Random Variables--NEW--', 'Expectation-of-a-Multiple-or-Sum-of-Random-Variables--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.880', @subjectID, @branchID, 'Conditional Expectation--NEW--', 'Conditional-Expectation--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.900', @subjectID, @branchID, 'Laws of Large Numbers--NEW--', 'Laws-of-Large-Numbers--NEW--', NULL, 'published', NOW() ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.910', @subjectID, @branchID, 'Describing a Probability Distribution--NEW--', 'Describing-a-Probability-Distribution--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.920', @subjectID, @branchID, 'Chebyshev Inequality--NEW--', 'Chebyshev-Inequality--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.930', @subjectID, @branchID, 'Weak Law of Large Numbers--NEW--', 'Weak-Law-of-Large-Numbers--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.940', @subjectID, @branchID, 'Central Limits--NEW--', 'Central-Limits--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.950', @subjectID, @branchID, 'Strong Law of Large Numbers--NEW--', 'Strong-Law-of-Large-Numbers--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
INSERT INTO `ConceptNodes` (`encodedID`, `subjectID`, `branchID`, `name`, `handle`, `parentID`, `status`, `created`) select 'MAT.PRB.960', @subjectID, @branchID, 'Comparison of Inequalities and Laws--NEW--', 'Comparison-of-Inequalities-and-Laws--NEW--', id, 'published', NOW() from `ConceptNodes` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `handle`=VALUES(`handle`), `parentID`=VALUES(`parentID`);
SELECT `id` INTO @subjectID FROM `Subjects` WHERE `shortname` = 'MAT';
SELECT `id` INTO @branchID FROM `Branches` WHERE `shortname` = 'PRB';
UPDATE `ConceptNodes` SET `name`=CONCAT(`name`,'--OLD--') WHERE (`name` NOT LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `name`=SUBSTR(`name`,1,LENGTH(`name`)-7) WHERE (`name` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
UPDATE `ConceptNodes` SET `handle`=SUBSTR(`handle`,1,LENGTH(`handle`)-7) WHERE (`handle` LIKE '%--NEW--') AND (`subjectID` = @subjectID) AND (`branchID` = @branchID);
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.101');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.100';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.101';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.110');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.101';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.110';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.120');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.110';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.120';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.130');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.120';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.130';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.140');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.130';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.140';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.150');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.140';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.150';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.200');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.150';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.200';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.210');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.200';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.210';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.220');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.210';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.220';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.230');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.220';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.230';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.240');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.230';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.240';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.250');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.240';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.250';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.260');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.250';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.260';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.270');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.260';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.270';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.300');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.270';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.300';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.310');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.300';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.310';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.312');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.310';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.312';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.314');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.312';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.314';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.316');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.314';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.316';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.320');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.316';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.320';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.321');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.320';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.321';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.322');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.321';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.322';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.324');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.322';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.324';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.326');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.324';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.326';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.330');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.326';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.330';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.332');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.330';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.332';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.334');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.332';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.334';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.340');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.334';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.340';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.350');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.340';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.350';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.360');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.350';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.360';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.370');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.360';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.370';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.400');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.370';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.400';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.410');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.400';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.410';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.420');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.410';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.420';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.421');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.420';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.421';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.422');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.421';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.422';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.423');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.422';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.423';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.424');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.423';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.424';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.425');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.424';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.425';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.426');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.425';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.426';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.430');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.426';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.430';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.440');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.430';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.440';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.450');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.440';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.450';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.460');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.450';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.460';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.470');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.460';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.470';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.480');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.470';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.480';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.490');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.480';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.490';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.500');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.490';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.500';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.510');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.500';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.510';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.520');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.510';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.520';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.530');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.520';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.530';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.540');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.530';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.540';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.550');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.540';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.550';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.560');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.550';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.560';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.561');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.560';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.561';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.570');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.561';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.570';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.600');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.570';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.600';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.610');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.600';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.610';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.612');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.610';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.612';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.614');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.612';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.614';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.616');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.614';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.616';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.618');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.616';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.618';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.620');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.618';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.620';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.621');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.620';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.621';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.621';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.622';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.1');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.622.1';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.2');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.1';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.622.2';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.3');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.2';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.622.3';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.623');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.622.3';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.623';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.624');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.623';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.624';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.625');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.624';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.625';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.626');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.625';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.626';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.627');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.626';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.627';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.630');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.627';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.630';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.632');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.630';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.632';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.640');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.632';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.640';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.642');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.640';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.642';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.644');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.642';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.644';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.646');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.644';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.646';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.700');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.646';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.700';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.720');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.700';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.720';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.730');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.720';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.730';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.732');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.730';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.732';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.740');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.732';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.740';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.800');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.740';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.800';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.820');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.800';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.820';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.840');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.820';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.840';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.860');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.840';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.860';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.880');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.860';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.880';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.900');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.880';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.900';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.910');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.900';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.910';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.920');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.910';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.920';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.930');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.920';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.930';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.940');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.930';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.940';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.950');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.940';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.950';
DELETE FROM `ConceptNodeNeighbors` WHERE `conceptNodeID` = (SELECT `id` FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.960');
SELECT `id` INTO @reqID FROM `ConceptNodes` WHERE `encodedID` = 'MAT.PRB.950';
INSERT INTO `ConceptNodeNeighbors` (`conceptNodeID`, `requiredConceptNodeID`) select id, @reqID from `ConceptNodes` where `encodedID` = 'MAT.PRB.960';
