INSERT INTO `ConceptKeywords` (`name`) VALUES ('Visible light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Visible light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.330';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Electromagnetic spectrum') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Electromagnetic spectrum';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.330';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light travels in straight lines') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light travels in straight lines';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.330';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light through a medium') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light through a medium';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.330';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light travels in straight lines') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light travels in straight lines';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.331';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light through a medium') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light through a medium';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.331';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Visible light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Visible light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.333';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Electromagnetic spectrum') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Electromagnetic spectrum';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.333';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Visible light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Visible light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Electromagnetic spectrum') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Electromagnetic spectrum';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Objects seen') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Objects seen';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light emitted by an object') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light emitted by an object';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light scattered from an object') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light scattered from an object';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light detected by the eye') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light detected by the eye';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('White light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'White light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Composition of White light,colors') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Composition of White light,colors';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Retinal cells') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Retinal cells';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reaction of retinal cells to wavelengths') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reaction of retinal cells to wavelengths';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.335';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Angle of reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Angle of reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Angle of incidence of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Angle of incidence of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.340';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.341';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.341';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.341';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.341';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.342';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.342';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.342';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.342';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light travels in straight lines') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light travels in straight lines';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light through a medium') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light through a medium';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.343';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.345';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.345';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.345';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.345';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.346';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.346';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.346';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.346';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.360';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.360';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.360';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.360';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Reflection of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Reflection of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.361';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Refraction of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Refraction of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.361';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Transmission of light') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Transmission of light';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.361';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);
INSERT INTO `ConceptKeywords` (`name`) VALUES ('Light absorbed by matter') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
SELECT `id` INTO @kwID FROM `ConceptKeywords` WHERE `name` = 'Light absorbed by matter';
SELECT `id` INTO @cnID FROM `ConceptNodes` WHERE `encodedID` = 'SCI.PHY.361';
INSERT IGNORE INTO `ConceptNodeHasKeywords` (`keywordID`, `conceptNodeID`) VALUES (@kwID, @cnID);


