INSERT IGNORE INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) values ('CKT', 'root', 4, NULL);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT','Mathematics',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI','Arithmetic',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.MEA','Measurement',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ALG','Algebra',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.CAL','Calculus',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.GEO','Geometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB','Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.STA','Statistics',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG','Trigonometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI','Science',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.CHE','Chemistry',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.PHY','Physics',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.BIO','Biology',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.ESC','Earth Science',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.100','Right Triangles and Introduction to Trigonometry',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.110','Pythagorean Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.112','Pythagorean Triples',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.110' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.114','Converse of Pythagorean Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.110' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.116','Distance Formula',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.110' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.120','Special Right Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.122','Isosceles Right Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.120' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.124','30-60-90 Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.120' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.126','Special Right Triangle Ratios',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.120' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.130','Basic Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.132','Sine and Cosine',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.130' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.134','Tangent and Cotangent',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.130' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.136','Secant and Cosecant',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.130' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.140','Solving Right Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.142','Inverse Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.140' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.144','Area of a Triangle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.140' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.146','Angles of Elevation and Depression',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.140' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.148','Applications of Right Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.140' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.150','Measuring Rotation',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.152','Angles of Rotation in Standard Position',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.150' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.154','Coterminal Angles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.150' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.160','Applying Trigonometric Functions to Angles of Rotation',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.162','Trigonometric Functions of Angles in Standard Position',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.160' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.164','The Unit Circle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.160' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.170','Trigonometric Functions of Any Angle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.172','Reference Angles and Angles in the Unit Circle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.170' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.174','Trigonometric Functions of Negative Angles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.170' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.176','Trigonometric Functions of Angles Greater than 360 Degrees',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.170' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.180','Trigonometric Function Relationships',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.182','Reciprocal Identities and Quotient Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.180' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.184','Domain/Range/Signs of Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.180' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.186','Cofunction Identities and Reflection',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.180' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.188','Pythagorean Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.180' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.200','Graphing Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.210','Radian Measure',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.212','Converting Degrees to Radians',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.210' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.214','Six Trigonometric Functions and Radians',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.210' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.220','Applications of Radian Measure',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.222','Rotations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.220' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.224','Length of an Arc and Length of a Chord',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.220' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.226','Area of a Sector',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.220' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.228','Angular Velocity',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.220' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.230','Circular Functions of Real Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.232','Sine Graph and Cosine Graph',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.230' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.234','Tangent Graph and Cotangent Graph',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.230' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.236','Secant Graph and Cosecant Graph',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.230' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.240','Translating Sine and Cosine Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.242','Vertical Translations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.240' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.244','Horizontal Translations or Phase Shifts',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.240' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.250','Amplitude, Period and Frequency',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.252','Amplitude',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.250' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.254','Period',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.250' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.256','Frequency',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.250' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.260','General Sinusoidal Graphs',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.262','Generalized Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.260' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.264','Identify Transformation from Equation',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.260' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.266','Writing Equation from Sketch',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.260' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.270','Graphing Tangent, Cotangent, Secant and Cosecant',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.272','Tangent',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.270' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.274','Cotangent',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.270' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.276','Secant',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.270' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.278','Cosecant',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.270' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.300','Trigonometric Identities and Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.310','Fundamental Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.312','Quotient and Reciprocal Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.314','Pythagorean Identity',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.316','Even and Odd Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.318','Cofunction Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.320','Solving Trigonometric Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.322','Simplifying Trigonometric Expressions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.324','Solving Trigonometric Equations Using Factoring',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.326','Solving Trigonometric Equations Using Quadratic Formula',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.330','Sum and Difference Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.332','Cosine',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.330' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.334','Sine',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.330' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.336','Tangent',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.330' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.340','Double Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.342','Deriving Double Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.340' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.344','Applying Double Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.340' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.346','Solving Equations with Double Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.340' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.350','Half-Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.352','Deriving Half-Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.350' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.354','Applying Half-Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.350' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.356','Solving Equations with Double Angle Identities',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.350' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.360','Products, Sums, Linear Combinations and Applications',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.362','Sum to Product and Product to Sum for Sine and Cosine',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.360' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.364','Solving Equations with Product & Sum Formulas',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.360' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.366','Triple Angle Formulas',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.360' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.368','Linear Combinations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.360' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.400','Inverse Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.410','Basic Inverse Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.412','Define Inverse of Trigonometric Ratios',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.410' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.414','Exact Values of Inverse Sine, Cosine, Tangent',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.410' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.416','Finding Inverses Algebraically',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.410' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.420','Graphing Inverse Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.422','Finding the Inverse by Mapping',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.424','Finding the Inverse of the Trigonometric Ratios',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.430','Inverse Trigonometric Properties',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.432','Comparing Trigonometric Functions and Their Inverses',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.430' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.434','Comparing Inverse Reciprocal Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.430' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.440','Applications and Models of Inverse Trigonometric Functions',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.500','Triangles and Vectors',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.510','Law of Cosines',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.512','Derive the Law of Cosines',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.510' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.514','Finding the Side of an Oblique Triangle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.510' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.516','Finding Any Angle of a Triangle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.510' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.518','Identify Accurate Drawings of General Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.510' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.520','Area of a Triangle',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.522','Heron\'s Formula',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.520' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.524','Finding a Part of a Triangle Given the Area',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.520' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.530','Law of Sines',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.532','AAS',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.530' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.534','ASA',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.530' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.536','Solving Triangles Using the Law of Sines',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.530' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.540','Ambiguous Case',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.542','Possible Triangles with SSA',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.540' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.550','General Solutions of Triangles',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.552','Summary of Triangle Techniques',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.550' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.560','Vectors',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.562','Vector Addition and Vector Subtraction',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.560' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.564','Resultant of Two Displacements',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.560' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.566','Directed Line Segments, Equal Vectors, Absolute Value',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.560' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.570','Component Vectors',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.572','Vector Multiplied by Scalar',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.570' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.574','Translation of Vectors and Slope',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.570' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.576','Unit Vectors & Components',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.570' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.578','Resultant as the Sum of Two Components; Resultant as Magnitude & Direction',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.570' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.600','Polar System',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.610','Polar Coordinates',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.612','Plotting Polar Coordinates',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.610' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.614','Distance Between Polar Coordinates',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.610' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.620','Graphing Basic Polar Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.622','Transformation of Polar Graphs',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.624','Graphing Polar Equations on the Calculator',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.630','Converting Between Systems',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.632','Polar to Rectangular',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.630' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.634','Rectangular to Polar',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.630' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.636','Converting Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.630' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.638','Converting Equations Using Graphing Calculator',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.630' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.640','Polar Curves',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.642','Intersections of Polar Curves',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.640' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.644','Equivalent Polar Curves',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.640' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.650','Trigonometric Form of Complex Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.652','Polar Form of a Complex Number',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.650' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.660','Product and Quotient Theorems',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.662','Product Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.660' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.664','Quotient Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.660' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.670','De Moivre\'s and the nth Root Theorems',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.672','De Moivre\'s Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.670' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.674','Roots',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.670' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG.676','Geometry of Complex Roots',4, id from `BrowseTerms` where `encodedID` = 'MAT.TRG.670' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);


DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.110');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.100';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.110';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.112');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.110';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.112';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.114');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.112';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.114';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.116');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.114';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.116';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.120');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.116';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.120';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.122');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.120';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.122';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.124');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.122';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.124';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.126');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.124';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.126';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.130');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.126';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.130';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.132');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.130';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.132';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.134');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.132';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.134';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.136');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.134';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.136';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.140');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.136';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.140';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.142');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.140';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.142';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.144');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.142';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.144';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.146');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.144';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.146';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.148');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.146';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.148';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.150');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.148';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.150';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.152');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.150';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.152';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.154');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.152';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.154';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.160');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.154';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.160';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.162');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.160';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.162';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.164');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.162';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.164';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.170');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.164';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.170';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.172');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.170';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.172';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.174');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.172';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.174';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.176');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.174';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.176';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.180');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.176';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.180';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.182');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.180';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.182';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.184');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.182';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.184';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.186');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.184';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.186';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.188');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.186';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.188';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.200');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.188';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.200';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.210');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.200';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.210';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.212');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.210';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.212';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.214');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.212';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.214';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.220');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.214';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.220';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.222');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.220';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.222';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.224');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.222';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.224';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.226');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.224';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.226';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.228');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.226';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.228';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.230');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.228';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.230';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.232');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.230';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.232';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.234');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.232';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.234';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.236');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.234';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.236';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.240');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.236';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.240';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.242');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.240';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.242';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.244');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.242';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.244';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.250');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.244';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.250';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.252');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.250';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.252';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.254');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.252';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.254';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.256');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.254';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.256';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.260');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.256';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.260';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.262');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.260';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.262';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.264');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.262';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.264';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.266');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.264';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.266';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.270');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.266';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.270';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.272');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.270';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.272';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.274');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.272';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.274';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.276');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.274';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.276';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.278');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.276';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.278';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.300');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.278';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.300';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.310');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.300';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.310';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.312');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.310';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.312';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.314');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.312';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.314';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.316');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.314';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.316';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.318');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.316';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.318';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.320');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.318';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.320';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.322');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.320';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.322';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.324');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.322';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.324';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.326');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.324';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.326';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.330');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.326';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.330';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.332');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.330';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.332';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.334');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.332';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.334';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.336');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.334';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.336';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.340');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.336';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.340';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.342');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.340';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.342';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.344');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.342';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.344';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.346');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.344';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.346';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.350');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.346';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.350';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.352');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.350';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.352';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.354');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.352';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.354';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.356');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.354';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.356';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.360');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.356';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.360';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.362');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.360';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.362';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.364');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.362';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.364';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.366');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.364';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.366';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.368');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.366';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.368';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.400');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.368';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.400';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.410');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.400';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.410';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.412');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.410';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.412';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.414');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.412';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.414';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.416');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.414';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.416';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.420');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.416';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.420';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.422');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.420';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.422';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.424');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.422';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.424';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.430');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.424';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.430';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.432');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.430';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.432';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.434');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.432';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.434';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.440');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.434';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.440';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.500');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.440';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.500';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.510');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.500';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.510';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.512');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.510';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.512';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.514');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.512';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.514';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.516');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.514';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.516';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.518');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.516';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.518';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.520');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.518';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.520';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.522');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.520';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.522';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.524');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.522';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.524';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.530');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.524';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.530';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.532');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.530';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.532';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.534');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.532';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.534';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.536');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.534';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.536';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.540');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.536';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.540';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.542');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.540';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.542';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.550');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.542';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.550';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.552');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.550';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.552';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.560');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.552';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.560';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.562');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.560';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.562';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.564');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.562';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.564';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.566');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.564';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.566';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.570');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.566';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.570';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.572');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.570';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.572';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.574');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.572';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.574';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.576');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.574';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.576';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.578');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.576';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.578';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.600');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.578';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.600';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.610');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.600';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.610';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.612');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.610';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.612';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.614');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.612';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.614';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.620');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.614';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.620';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.622');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.620';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.622';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.624');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.622';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.624';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.630');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.624';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.630';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.632');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.630';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.632';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.634');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.632';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.634';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.636');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.634';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.636';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.638');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.636';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.638';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.640');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.638';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.640';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.642');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.640';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.642';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.644');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.642';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.644';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.650');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.644';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.650';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.652');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.650';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.652';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.660');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.652';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.660';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.662');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.660';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.662';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.664');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.662';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.664';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.670');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.664';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.670';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.672');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.670';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.672';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.674');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.672';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.674';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.676');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.TRG.674';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.TRG.676';

