INSERT IGNORE INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) values ('CKT', 'root', 4, NULL);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT','Mathematics',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI','Arithmetic',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.MEA','Measurement',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ALG','Algebra',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.CAL','Calculus',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.GEO','Geometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB','Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.STA','Statistics',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG','Trigonometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI','Science',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.CHE','Chemistry',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.PHY','Physics',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.BIO','Biology',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.ESC','Earth Science',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.100','Theoretical and Experimental Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.110','Measurement of Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.120','Empirical Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.130','Subjective Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.140','How Probability is Applied',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.150','Applications of Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.200','Set Theory',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.210','Sets',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.220','Venn Diagrams',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.230','Subsets',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.240','Sample Spaces and Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.250','Special Sets, Empty Set, Universal Set',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.260','Operations with Sets',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.270','Properties of Set Operations',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.300','Counting Techniques',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.310','Counting Principles',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.312','Product Rule for Counting',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.314','Sum Rule for Counting',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.310' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.320','Probability and Permutations',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.322','Permutations and Combinations Compared',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.324','Permutation Problems',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.326','Permutations with Repetition',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.320' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.330','Probability and Combinations',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.332','Combinations',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.330' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.334','Combination Problems',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.330' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.340','Partitions',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.350','Challenging Counting Problems',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.360','Binomial Coefficients',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.370','Pascal\'s Triangle',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.400','Probability of Compound Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.410','Numerical Computations',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.420','Tree Diagrams',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.421','Counting Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.422','Multiplication Rule for Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.423','Complement Rule for Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.424','Mutually Exclusive Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.425','Mutually Inclusive Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.426','Inequality for Probabilities',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.420' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.430','Problems Using Dice',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.440','Problems Involving Coin Tossing',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.450','Problems Involving Cards',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.460','Geometric Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.470','Quality Control',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.480','Birthday Problems',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.490','Transmission Errors',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.500','Conditional Probability and Independence',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.510','Conditional Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.520','Multiplication Theorem for Conditional Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.530','Switching Conditions',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.540','Partitions and the Law of Total Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.550','Bayes\' Formula for Conditional Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.560','Independent Events',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.600','Discrete Random Variables and Continuous Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.610','Discrete Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.612','Discrete Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.614','The Probability Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.616','Cumulative Distribution Function of a Random Variable',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.610' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.620','Types of Distribution of Discrete Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.621','Joint Distribution of Two Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.622','The Bernoulli Random Variable and the Binomial Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.622.1','Binomial Distributions and Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.622.2','Binompdf Function',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.622.3','Binomcdf Function',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.622' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.623','The Poisson Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.624','The Geometric Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.625','The Negative Binomial Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.626','The Hypergeometric Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.627','Multinomial Distributions',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.620' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.630','Continuous Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.632','Cumulative Distribution Function of a Continuous Random Variable',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.630' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.640','Types of Distribution of Continuous Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.642','The Uniform Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.644','The Normal Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.646','Exponential Distributions',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.640' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.700','Properties of the Normal Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.720','Computing Probabilities for the Standard Normal Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.730','Empirical Rule',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.732','Linear Interpolation of Normal Distributions',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.730' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.740','The Normal Approximation of the Binomial Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.800','Expected Value',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.820','Expected Value for Discrete Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.840','Expected Value for Continuous Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.860','Expectation of a Multiple or Sum of Random Variables',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.880','Conditional Expectation',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.800' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.900','Laws of Large Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.910','Describing a Probability Distribution',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.920','The Chebyshev Inequality',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.930','The Weak Law of Large Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.940','The Central Limit Theorem',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.950','The Strong Law of Large Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB.960','Comparison of Inequalities and Laws',4, id from `BrowseTerms` where `encodedID` = 'MAT.PRB.900' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);


DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.110');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.100';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.110';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.120');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.110';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.120';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.130');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.120';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.130';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.140');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.130';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.140';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.150');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.140';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.150';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.200');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.150';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.200';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.210');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.200';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.210';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.220');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.210';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.220';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.230');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.220';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.230';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.240');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.230';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.240';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.250');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.240';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.250';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.260');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.250';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.260';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.270');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.260';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.270';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.300');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.270';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.300';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.310');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.300';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.310';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.312');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.310';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.312';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.314');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.312';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.314';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.320');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.314';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.320';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.322');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.320';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.322';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.324');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.322';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.324';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.326');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.324';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.326';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.330');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.326';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.330';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.332');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.330';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.332';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.334');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.332';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.334';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.340');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.334';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.340';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.350');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.340';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.350';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.360');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.350';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.360';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.370');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.360';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.370';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.400');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.370';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.400';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.410');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.400';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.410';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.420');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.410';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.420';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.421');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.420';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.421';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.422');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.421';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.422';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.423');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.422';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.423';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.424');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.423';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.424';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.425');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.424';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.425';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.426');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.425';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.426';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.430');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.426';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.430';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.440');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.430';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.440';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.450');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.440';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.450';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.460');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.450';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.460';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.470');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.460';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.470';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.480');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.470';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.480';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.490');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.480';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.490';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.500');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.490';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.500';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.510');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.500';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.510';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.520');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.510';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.520';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.530');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.520';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.530';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.540');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.530';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.540';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.550');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.540';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.550';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.560');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.550';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.560';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.600');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.560';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.600';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.610');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.600';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.610';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.612');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.610';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.612';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.614');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.612';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.614';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.616');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.614';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.616';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.620');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.616';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.620';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.621');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.620';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.621';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.621';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.622';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.1');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.622.1';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.2');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.1';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.622.2';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.3');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.2';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.622.3';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.623');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.622.3';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.623';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.624');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.623';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.624';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.625');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.624';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.625';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.626');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.625';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.626';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.627');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.626';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.627';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.630');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.627';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.630';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.632');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.630';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.632';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.640');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.632';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.640';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.642');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.640';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.642';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.644');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.642';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.644';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.646');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.644';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.646';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.700');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.646';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.700';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.720');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.700';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.720';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.730');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.720';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.730';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.732');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.730';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.732';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.740');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.732';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.740';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.800');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.740';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.800';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.820');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.800';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.820';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.840');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.820';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.840';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.860');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.840';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.860';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.880');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.860';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.880';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.900');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.880';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.900';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.910');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.900';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.910';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.920');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.910';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.920';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.930');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.920';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.930';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.940');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.930';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.940';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.950');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.940';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.950';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.960');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.PRB.950';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.PRB.960';

