INSERT IGNORE INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) values ('CKT', 'root', 4, NULL);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT','Mathematics',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI','Arithmetic',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.MEA','Measurement',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ALG','Algebra',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.CAL','Calculus',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.GEO','Geometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.PRB','Probability',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.STA','Statistics',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.TRG','Trigonometry',4, id from `BrowseTerms` where `encodedID` = 'MAT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI','Science',4, id from `BrowseTerms` where `encodedID` = 'CKT' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.CHE','Chemistry',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.PHY','Physics',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.BIO','Biology',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'SCI.ESC','Earth Science',4, id from `BrowseTerms` where `encodedID` = 'SCI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.100','Whole Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.110','Addition of Integers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.120','Whole Number Subtraction',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.130','Whole Number Multiplication',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.132','Whole Number Exponents',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.130' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.140','Whole Number Division',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.150','Estimation and Rounding',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.160','Prime and Composite Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.170','Factors, Multiples, Divisibility',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.180','Greatest Common Factor',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.190','Least Common Multiple',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.100' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.200','Decimals',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.210','Decimal Addition',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.220','Decimal Subtraction',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.230','Decimal Multiplication',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.240','Decimal Division',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.250','Decimal Estimating and Rounding',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.260','Scientific Notation with Whole Number Exponents',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.200' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.300','Properties of Rational Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.310','Proper Fractions, Improper Fractions, Mixed Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.320','Equivalent Fractions',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.300' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.400','Applications of Reciprocals',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.410','Addition of Rational Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.420','Subtraction of Rational Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.430','Multiplication of Rational Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.440','Division of Rational Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.450','Estimating Fractions',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.400' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.500','Order of Real Numbers',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.510','Converting Fractions to Decimals',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.520','Converting Decimals to Fractions',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.500' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.600','Equations with Ratios and Proportions',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.610','Ratios',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.620','Rates',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.630','Proportions',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.600' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.700','Percents',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.710','Converting a Decimal to a Percent',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.720','Converting a Percent to a Decimal',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.730','Converting a Fraction to a Percent',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.740','Converting a Percent to a Fraction',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.750','Conversion of Decimals, Fractions, and Percent',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.760','Percent Equations',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);
INSERT  INTO `BrowseTerms` (`encodedID`, `name`, `termTypeID`, `parentID`) select 'MAT.ARI.770','Percent of Change',4, id from `BrowseTerms` where `encodedID` = 'MAT.ARI.700' ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `parentID` = VALUES(`parentID`);


DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.110');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.100';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.110';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.120');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.110';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.120';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.130');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.120';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.130';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.132');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.130';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.132';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.140');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.132';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.140';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.150');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.140';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.150';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.160');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.150';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.160';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.170');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.160';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.170';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.180');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.170';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.180';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.190');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.180';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.190';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.200');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.190';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.200';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.210');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.200';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.210';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.220');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.210';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.220';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.230');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.220';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.230';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.240');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.230';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.240';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.250');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.240';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.250';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.260');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.250';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.260';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.300');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.260';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.300';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.310');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.300';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.310';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.320');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.310';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.320';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.400');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.320';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.400';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.410');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.400';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.410';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.420');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.410';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.420';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.430');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.420';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.430';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.440');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.430';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.440';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.450');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.440';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.450';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.500');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.450';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.500';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.510');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.500';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.510';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.520');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.510';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.520';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.600');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.520';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.600';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.610');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.600';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.610';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.620');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.610';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.620';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.630');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.620';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.630';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.700');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.630';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.700';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.710');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.700';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.710';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.720');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.710';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.720';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.730');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.720';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.730';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.740');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.730';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.740';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.750');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.740';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.750';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.760');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.750';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.760';
DELETE FROM `DomainNeighbors` WHERE `domainID` = (SELECT `id` FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.770');
SELECT `id` INTO @reqID FROM `BrowseTerms` WHERE `encodedID` = 'MAT.ARI.760';
INSERT INTO `DomainNeighbors` (`domainID`, `requiredDomainID`) select id, @reqID from BrowseTerms where `encodedID` = 'MAT.ARI.770';

