ENVIRONMENT_PROPS = { 
    "FLX2_HOST": "flx2-host", 
}

CK12_XML_NAMESPACE = "http://www.ck12.org/ns/fbs2.0"

def genURLSafeBase64Encode(string):
    """ Returns a URL-safe Base64 encode of the string with '=' replaced with
    '_' after the encode. """
    from base64 import urlsafe_b64encode
    string = string.strip()
    id = urlsafe_b64encode(string).replace('=', '.')
    return 'x-ck12-%s' % id

def genURLSafeBase64Decode(encoded_string):
    """ Returns the decoded string of the base64 encode generated by
    genURLSafeBase64Encode function. """
    from base64 import urlsafe_b64decode
    if encoded_string.startswith('x-ck12-'):
        encoded_string = encoded_string[7:]
    return urlsafe_b64decode(encoded_string.replace('.', '='))

def truncateToBookmarkNameSize(str):
    str = str.replace(" ", "_")
    return str[:40]


COLOR_CODES = {
        'aqua':'00FFFF',
        'black':'000000',
        'blue':'0000FF',
        'fuchsia':'FF00FF',
        'gray':'808080',
        'grey':'808080',
        'green':'008000',
        'lime':'00FF00',
        'maroon':'800000',
        'navy':'000080',
        'olive':'808000',
        'purple':'800080',
        'red':'FF0000',
        'silver':'C0C0C0',
        'teal':'008080',
        'white':'FFFFFF',
        'yellow':'FFFF00',  
        }
