class ErrorCodes:
    OK = 0

    REQUIRED_PARAMS_MISSING = 1000

    UNKNOWN_MEMBER = 1001
    CANNOT_CREATE_MEMBER = 1002
    CANNOT_CREATE_BROWSE_TERM = 1003
    CANNOT_CREATE_BROWSE_TERM_ASSOCIATION = 1004
    CANNOT_CREATE_STANDARD = 1005
    CANNOT_CREATE_STANDARD_ASSOCIATION = 1006
    CANNOT_CREATE_FEEDBACK = 1007
    CANNOT_CREATE_ARTIFACT = 1008
    AUTHENTICATION_REQUIRED = 1009
    CANNOT_PUBLISH_ARTIFACT = 1010
    UNAUTHORIZED_OPERATION = 1011
    CANNOT_DELETE_ARTIFACT = 1012
    CANNOT_CREATE_OVERLAY = 1013
    CANNOT_CREATE_ANNOTATION = 1014
    CANNOT_CREATE_BROWSE_TERM_SYNONYM = 1015
    CANNOT_LOAD_BROWSE_TERM_DATA = 1016
    CANNOT_CREATE_INDEX = 1017
    CANNOT_UPDATE_INDEX = 1018
    CANNOT_UPDATE_MEMBER = 1019
    CANNOT_UPDATE_RESOURCE_HASH = 1020
    CANNOT_CREATE_RESOURCE = 1021
    CANNOT_UPDATE_RESOURCE = 1022
    CANNOT_DELETE_RESOURCE = 1023
    CANNOT_CREATE_RESOURCE_ASSOCIATION = 1024
    CANNOT_DELETE_RESOURCE_ASSOCIATION = 1025
    CANNOT_DELETE_FEEDBACK = 1026
    CANNOT_IMPORT_XDT_DATA = 1027
    CANNOT_EXPORT_XDT_DATA = 1028
    CANNOT_REGISTER_APP = 1029
    CANNOT_IMPORT_FROM_WIKI = 1030
    ALREADY_ACTIVATED_MEMBER = 1031
    LOGIN_BEING_USED_ALREADY = 1032
    CANNOT_CREATE_FAVORITE = 1033
    CANNOT_DELETE_FAVORITE = 1034
    FAVORITE_ALREADY_EXIST = 1034
    CANNOT_CREATE_FEATURED_ARTIFACT = 1035
    CANNOT_DELETE_FEATURED_ARTIFACT = 1036
    CANNOT_GET_FEATURED_ARTIFACT_LIST = 1037
    ARTIFACT_ALREADY_EXIST = 1038
    CANNOT_LOAD_BROWSE_CANDIDATE_DATA = 1039
    ALREADY_LOGGED_IN = 1040
    CANNOT_UPDATE_ARTIFACT = 1041
    CANNOT_CREATE_EMBEDDED_OBJECT = 1042
    CANNOT_UPDATE_EMBEDDED_OBJECT_PROVIDER = 1043
    CANNOT_CREATE_ABUSE_REPORT = 1044
    CANNOT_UPDATE_ABUSE_REPORT = 1045
    AUTHENTICATION_REJECTED = 1046
    AUTHENTICATION_FAILED = 1047
    LOGIN_REQUIRED = 1048
    MEMBER_INTERACTION_NEEDED = 1049
    CANNOT_CREATE_EMBEDDED_OBJECT_PROVIDER = 1050
    CANNOT_IMPORT_GDT_DATA = 1051
    CANNOT_EXPORT_GDT_DATA = 1052
    CANNOT_IMPORT_FROM_ZIP = 1053
    CANNOT_CONVERT_GDT2EPUB = 1054
    CANNOT_IMPORT_CONCEPT_MAP = 1055
    CANNOT_CREATE_MATH_CACHE = 1056
    CANNOT_CREATE_NOTIFICATION = 1057
    CANNOT_UPDATE_NOTIFICATION = 1058
    CANNOT_DELETE_NOTIFICATION = 1059
    CANNOT_LIST_GOOGLE_DOCUMENTS = 1060
    CANNOT_ADD_OBJECT_TO_LIBRARY = 1061
    CANNOT_REMOVE_OBJECT_FROM_LIBRARY = 1062
    CANNOT_CREATE_LABEL = 1063
    CANNOT_DELETE_LABEL = 1064
    CANNOT_ASSIGN_LABEL_TO_LIBRARY_OBJECT = 1065
    CANNOT_REMOVE_LABEL_FROM_LIBRARY_OBJECT = 1066
    CANNOT_UPDATE_LABEL = 1067
    CANNOT_DELETE_BROWSE_TERM_ASSOCIATION = 1069
    CANNOT_UNPUBLISH_ARTIFACT = 1070
    RESOURCE_TOO_LARGE = 1071
    INVALID_SEARCH_QUERY = 1072
    RESOURCE_ALREADY_EXISTS = 1073
    EMBEDDED_OBJECT_PROVIDER_ALREADY_EXISTS = 1074
    DUPLICATE_CHAPTER_TITLE = 1075
    LABEL_ALREADY_EXISTS = 1076
    CANNOT_LOAD_MODALITY_DATA = 1077
    LABEL_ALREADY_EXISTS = 1078
    CANNOT_LOAD_VOCABULARY_DATA = 1079
    CANNOT_INVALIDATE_CACHE = 1080
    CANNOT_CREATE_OAUTH_CLIENT = 1081
    CANNOT_UPDATE_OAUTH_CLIENT = 1082
    CANNOT_UPLOAD_DATA = 1083
    CANNOT_SEND_EMAIL = 1084
    MEMBER_EMAIL_ALREADY_VERIFIED = 1084
    INVALID_ARGUMENT = 1085

    UNKNOWN_ARTIFACT_TYPE = 2001
    NO_SUCH_ARTIFACT = 2002
    NO_SUCH_BOOK = 2003
    NO_SUCH_CHAPTER = 2004
    FORMAT_NOT_SUPPORTED = 2005
    NO_SUCH_BROWSE_TERM = 2006
    NO_SUCH_COUNTRY = 2007
    NO_SUCH_STANDARD = 2008
    NO_SUCH_LESSON = 2009
    NO_SUCH_CONCEPT = 2010
    NO_SUCH_MEMBER = 2011
    NO_SUCH_STATE = 2012
    NO_SUCH_OVERLAY = 2013
    NO_SUCH_ANNOTATION = 2014
    RETRIEVAL_ERROR = 2015
    NO_SUCH_TASK = 2016
    NO_SUCH_FEEDBACK = 2017
    NO_SUCH_RESOURCE = 2018
    NO_SUCH_FAVORITE = 2019
    NO_SUCH_FEATURED_ARTIFACT = 2020
    UNKNOWN_REALM_TYPE = 2021
    INVALID_VERSION = 2022
    NO_SUCH_BROWSE_CANDIDATE = 2023
    NO_SUCH_BROWSE_CATEGORY = 2024
    UNKNOWN_RESOURCE_TYPE = 2025
    NO_SUCH_EMBEDDED_OBJECT = 2026
    NO_SUCH_EMBEDDED_OBJECT_PROVIDER = 2027
    FORBIDDEN_EMBEDDED_OBJECT = 2028
    FORBIDDEN_RESOURCE = 2029
    NO_SUCH_ABUSE_REPORT = 2030
    NO_SUCH_APPROVAL_DOMAIN = 2031
    VALIDATION_FAILED = 2032
    NOT_AUTHORIZED_TO_PRINT = 2033
    NO_SUCH_NOTIFICATION = 2034
    NO_SUCH_LABEL = 2035
    NO_SUCH_GOOGLEDOC_AUTH = 2036
    INVALID_HTML_CONTENT = 2037
    NO_SUCH_EVENT_TYPE = 2038
    NO_SUCH_NOTIFICATION_RULE = 2039
    NO_SUCH_EVENT = 2040
    NO_SUCH_SUBJECT = 2041
    NO_SUCH_GRADE = 2042
    NO_SUCH_STANDARD_BOARD = 2043
    NO_SUCH_STANDARD_CORRELATION = 2044
    CANNOT_CREATE_EVENT  = 2045
    SUGGESTION_RETRIEVAL_ERROR = 2046
    NO_SUCH_VOCABULARY = 2047
    NO_SUCH_LANGUAGE = 2048
    NO_SUCH_OAUTH_CLIENT = 2049
    INVALID_EMAIL = 2050
    MISSING_PASSWORD = 2051
    INVALID_LTI_CONSUMER_KEY = 2052

    CANNOT_CREATE_WORKSHEET = 3015

    CANNOT_GET_DOWNLOADCOUNT  = 4001
    CANNOT_GET_DOWNLOADSTATSTYPES  = 4002
    CANNOT_UPDATE_DOWNLOADSTATS  = 4002
    CANNOT_ADD_DOWNLOADSTATSTYPE  = 4003
    CANNOT_DELETE_DOWNLOADSTATSTYPE  = 4003
 
    CANNOT_CREATE_GROUP = 5001
    CANNOT_UPDATE_GROUP = 5002
    CANNOT_DELETE_GROUP = 5003
    NO_SUCH_GROUP = 5004
    CANNOT_ADD_MEMBER_TO_GROUP = 5005
    CANNOT_DELETE_MEMBER_FROM_GROUP = 5006
    UNABLE_TO_GET_MEMBERS = 5007
    CANNOT_ACTIVATE_GROUP_MEMBER = 5008
    CANNOT_DECLINE_GROUP_MEMBER = 5009
    GROUP_ALREADY_EXISTS = 5010
    MEMBER_ALREADY_EXISTS = 5011
    MEMBER_ROLE_CONFLICT = 5012
    MEMBER_ALREADY_ASSOCIATED = 5013

    GENERIC_ERROR = 1000000

    errorDesc = {}

    def __init__(self):
        self.errorDesc[self.OK] = { 'name':'OK' }
        self.errorDesc[self.REQUIRED_PARAMS_MISSING] = { 'name':'REQUIRED_PARAMS_MISSING' }
        self.errorDesc[self.UNKNOWN_MEMBER] = { 'name':'UNKNOWN_MEMBER' }
        self.errorDesc[self.CANNOT_CREATE_MEMBER] = { 'name':'CANNOT_CREATE_MEMBER' }
        self.errorDesc[self.CANNOT_CREATE_BROWSE_TERM] = { 'name':'CANNOT_CREATE_BROWSE_TERM' }
        self.errorDesc[self.CANNOT_CREATE_BROWSE_TERM_ASSOCIATION] = { 'name':'CANNOT_CREATE_BROWSE_TERM_ASSOCIATION' }
        self.errorDesc[self.CANNOT_CREATE_STANDARD] = { 'name':'CANNOT_CREATE_STANDARD' }
        self.errorDesc[self.CANNOT_CREATE_STANDARD_ASSOCIATION] = { 'name':'CANNOT_CREATE_STANDARD_ASSOCIATION' }
        self.errorDesc[self.CANNOT_CREATE_FEEDBACK] = { 'name':'CANNOT_CREATE_FEEDBACK' }
        self.errorDesc[self.CANNOT_CREATE_ARTIFACT] = { 'name':'CANNOT_CREATE_ARTIFACT' }
        self.errorDesc[self.AUTHENTICATION_REQUIRED] = { 'name':'AUTHENTICATION_REQUIRED' }
        self.errorDesc[self.CANNOT_PUBLISH_ARTIFACT] = { 'name':'CANNOT_PUBLISH_ARTIFACT' }
        self.errorDesc[self.UNAUTHORIZED_OPERATION] = { 'name':'UNAUTHORIZED_OPERATION' }
        self.errorDesc[self.CANNOT_DELETE_ARTIFACT] = { 'name':'CANNOT_DELETE_ARTIFACT' }
        self.errorDesc[self.CANNOT_CREATE_OVERLAY] = { 'name':'CANNOT_CREATE_OVERLAY' }
        self.errorDesc[self.CANNOT_CREATE_ANNOTATION] = { 'name':'CANNOT_CREATE_ANNOTATION' }
        self.errorDesc[self.CANNOT_CREATE_BROWSE_TERM_SYNONYM] = { 'name':'CANNOT_CREATE_BROWSE_TERM_SYNONYM' }
        self.errorDesc[self.CANNOT_LOAD_BROWSE_TERM_DATA] = { 'name':'CANNOT_LOAD_BROWSE_TERM_DATA' }
        self.errorDesc[self.CANNOT_CREATE_INDEX] = { 'name':'CANNOT_CREATE_INDEX' }
        self.errorDesc[self.CANNOT_UPDATE_INDEX] = { 'name':'CANNOT_UPDATE_INDEX' }
        self.errorDesc[self.CANNOT_UPDATE_MEMBER] = { 'name':'CANNOT_UPDATE_MEMBER' }
        self.errorDesc[self.CANNOT_UPDATE_RESOURCE_HASH] = { 'name':'CANNOT_UPDATE_RESOURCE_HASH' }
        self.errorDesc[self.CANNOT_CREATE_RESOURCE] = { 'name':'CANNOT_CREATE_RESOURCE' }
        self.errorDesc[self.CANNOT_UPDATE_RESOURCE] = { 'name':'CANNOT_UPDATE_RESOURCE' }
        self.errorDesc[self.CANNOT_DELETE_RESOURCE] = { 'name':'CANNOT_DELETE_RESOURCE' }
        self.errorDesc[self.CANNOT_CREATE_RESOURCE_ASSOCIATION] = { 'name':'CANNOT_CREATE_RESOURCE_ASSOCIATION' }
        self.errorDesc[self.CANNOT_DELETE_RESOURCE_ASSOCIATION] = { 'name':'CANNOT_DELETE_RESOURCE_ASSOCIATION' }
        self.errorDesc[self.CANNOT_DELETE_FEEDBACK] = { 'name':'CANNOT_DELETE_FEEDBACK' }
        self.errorDesc[self.CANNOT_IMPORT_XDT_DATA] = { 'name':'CANNOT_IMPORT_XDT_DATA' }
        self.errorDesc[self.CANNOT_EXPORT_XDT_DATA] = { 'name':'CANNOT_EXPORT_XDT_DATA' }
        self.errorDesc[self.CANNOT_REGISTER_APP] = { 'name':'CANNOT_REGISTER_APP' }
        self.errorDesc[self.CANNOT_IMPORT_FROM_WIKI] = { 'name':'CANNOT_IMPORT_FROM_WIKI' }
        self.errorDesc[self.ALREADY_ACTIVATED_MEMBER] = { 'name':'ALREADY_ACTIVATED_MEMBER' }
        self.errorDesc[self.LOGIN_BEING_USED_ALREADY] = { 'name':'LOGIN_BEING_USED_ALREADY' }
        self.errorDesc[self.CANNOT_CREATE_FAVORITE] = { 'name':'CANNOT_CREATE_FAVORITE' }
        self.errorDesc[self.CANNOT_DELETE_FAVORITE] = { 'name':'CANNOT_DELETE_FAVORITE' }
        self.errorDesc[self.FAVORITE_ALREADY_EXIST] = { 'name':'FAVORITE_ALREADY_EXIST' }
        self.errorDesc[self.CANNOT_CREATE_FEATURED_ARTIFACT] = { 'name':'CANNOT_CREATE_FEATURED_ARTIFACT' }
        self.errorDesc[self.CANNOT_DELETE_FEATURED_ARTIFACT] = { 'name':'CANNOT_DELETE_FEATURED_ARTIFACT' }
        self.errorDesc[self.CANNOT_GET_FEATURED_ARTIFACT_LIST] = { 'name':'CANNOT_GET_FEATURED_ARTIFACT_LIST' }
        self.errorDesc[self.ARTIFACT_ALREADY_EXIST] = { 'name':'ARTIFACT_ALREADY_EXIST' }
        self.errorDesc[self.CANNOT_LOAD_BROWSE_CANDIDATE_DATA] = { 'name': 'CANNOT_LOAD_BROWSE_CANDIDATE_DATA' }
        self.errorDesc[self.ALREADY_LOGGED_IN] = { 'name': 'ALREADY_LOGGED_IN' }
        self.errorDesc[self.CANNOT_UPDATE_EMBEDDED_OBJECT_PROVIDER] = { 'name': 'CANNOT_UPDATE_EMBEDDED_OBJECT_PROVIDER' }
        self.errorDesc[self.CANNOT_CREATE_ABUSE_REPORT] = { 'name': 'CANNOT_CREATE_ABUSE_REPORT' }
        self.errorDesc[self.CANNOT_UPDATE_ABUSE_REPORT] = { 'name': 'CANNOT_UPDATE_ABUSE_REPORT' }
        self.errorDesc[self.AUTHENTICATION_REJECTED] = { 'name': 'AUTHENTICATION_REJECTED' }
        self.errorDesc[self.AUTHENTICATION_FAILED] = { 'name': 'AUTHENTICATION_FAILED' }
        self.errorDesc[self.LOGIN_REQUIRED] = { 'name': 'LOGIN_REQUIRED' }
        self.errorDesc[self.MEMBER_INTERACTION_NEEDED] = { 'name': 'MEMBER_INTERACTION_NEEDED' }
        self.errorDesc[self.CANNOT_CREATE_EMBEDDED_OBJECT_PROVIDER] = {'name': 'CANNOT_CREATE_EMBEDDED_OBJECT_PROVIDER' }
        self.errorDesc[self.CANNOT_IMPORT_GDT_DATA] = { 'name':'CANNOT_IMPORT_GDT_DATA' }
        self.errorDesc[self.CANNOT_EXPORT_GDT_DATA] = { 'name':'CANNOT_EXPORT_GDT_DATA' }
        self.errorDesc[self.CANNOT_CONVERT_GDT2EPUB] = { 'name':'CANNOT_CONVERT_GDT2EPUB' }
        self.errorDesc[self.CANNOT_IMPORT_CONCEPT_MAP] = { 'name':'CANNOT_IMPORT_CONCEPT_MAP' }
        self.errorDesc[self.CANNOT_CREATE_MATH_CACHE] = { 'name':'CANNOT_CREATE_MATH_CACHE' }
        self.errorDesc[self.CANNOT_CREATE_NOTIFICATION] = { 'name':'CANNOT_CREATE_NOTIFICATION' }
        self.errorDesc[self.CANNOT_UPDATE_NOTIFICATION] = { 'name':'CANNOT_UPDATE_NOTIFICATION' }
        self.errorDesc[self.CANNOT_DELETE_NOTIFICATION] = { 'name':'CANNOT_DELETE_NOTIFICATION' }
        self.errorDesc[self.CANNOT_LIST_GOOGLE_DOCUMENTS] = { 'name':'CANNOT_LIST_GOOGLE_DOCUMENTS' }
        self.errorDesc[self.CANNOT_ADD_OBJECT_TO_LIBRARY] = { 'name': 'CANNOT_ADD_OBJECT_TO_LIBRARY' }
        self.errorDesc[self.CANNOT_REMOVE_OBJECT_FROM_LIBRARY] = { 'name': 'CANNOT_REMOVE_OBJECT_FROM_LIBRARY'}
        self.errorDesc[self.CANNOT_CREATE_LABEL] = { 'name': 'CANNOT_CREATE_LABEL' }
        self.errorDesc[self.CANNOT_UPDATE_LABEL] = { 'name': 'CANNOT_UPDATE_LABEL' }
        self.errorDesc[self.CANNOT_DELETE_LABEL] = { 'name': 'CANNOT_DELETE_LABEL' }
        self.errorDesc[self.CANNOT_ASSIGN_LABEL_TO_LIBRARY_OBJECT] = { 'name': 'CANNOT_ASSIGN_LABEL_TO_LIBRARY_OBJECT' }
        self.errorDesc[self.CANNOT_REMOVE_LABEL_FROM_LIBRARY_OBJECT] = { 'name': 'CANNOT_REMOVE_LABEL_FROM_LIBRARY_OBJECT' }
        self.errorDesc[self.CANNOT_DELETE_BROWSE_TERM_ASSOCIATION] = { 'name': 'CANNOT_DELETE_BROWSE_TERM_ASSOCIATION' }
        self.errorDesc[self.CANNOT_UNPUBLISH_ARTIFACT] = { 'name': 'CANNOT_UNPUBLISH_ARTIFACT' }
        self.errorDesc[self.RESOURCE_TOO_LARGE] = { 'name': 'RESOURCE_TOO_LARGE' }
        self.errorDesc[self.INVALID_SEARCH_QUERY] = { 'name': 'INVALID_SEARCH_QUERY' }
        self.errorDesc[self.RESOURCE_ALREADY_EXISTS] = { 'name': 'RESOURCE_ALREADY_EXISTS' }
        self.errorDesc[self.EMBEDDED_OBJECT_PROVIDER_ALREADY_EXISTS] = { 'name': 'EMBEDDED_OBJECT_PROVIDER_ALREADY_EXISTS' }
        self.errorDesc[self.DUPLICATE_CHAPTER_TITLE] = { 'name': 'DUPLICATE_CHAPTER_TITLE' }
        self.errorDesc[self.LABEL_ALREADY_EXISTS] = { 'name': 'LABEL_ALREADY_EXISTS' }
        self.errorDesc[self.CANNOT_LOAD_MODALITY_DATA] = { 'name': 'CANNOT_LOAD_MODALITY_DATA' }
        self.errorDesc[self.CANNOT_INVALIDATE_CACHE] = { 'name': 'CANNOT_INVALIDATE_CACHE' }
        self.errorDesc[self.CANNOT_LOAD_VOCABULARY_DATA] = { 'name': 'CANNOT_LOAD_VOCABULARY_DATA' }
        self.errorDesc[self.CANNOT_CREATE_OAUTH_CLIENT] = { 'name': 'CANNOT_CREATE_OAUTH_CLIENT' }
        self.errorDesc[self.CANNOT_UPDATE_OAUTH_CLIENT] = { 'name': 'CANNOT_UPDATE_OAUTH_CLIENT' }
        self.errorDesc[self.CANNOT_UPLOAD_DATA] = { 'name': 'CANNOT_UPLOAD_DATA' }
        self.errorDesc[self.MEMBER_EMAIL_ALREADY_VERIFIED ] = { 'name': 'MEMBER_EMAIL_ALREADY_VERIFIED' }
        self.errorDesc[self.INVALID_ARGUMENT ] = { 'name': 'INVALID_ARGUMENT' }

        self.errorDesc[self.UNKNOWN_ARTIFACT_TYPE] = { 'name':'UNKNOWN_ARTIFACT_TYPE' }
        self.errorDesc[self.NO_SUCH_ARTIFACT] = { 'name':'NO_SUCH_ARTIFACT' }
        self.errorDesc[self.NO_SUCH_BOOK] = { 'name':'NO_SUCH_BOOK' }
        self.errorDesc[self.NO_SUCH_CHAPTER] = { 'name':'NO_SUCH_CHAPTER' }
        self.errorDesc[self.FORMAT_NOT_SUPPORTED] = { 'name':'FORMAT_NOT_SUPPORTED' }
        self.errorDesc[self.NO_SUCH_BROWSE_TERM] = { 'name':'NO_SUCH_BROWSE_TERM' }
        self.errorDesc[self.NO_SUCH_COUNTRY] = { 'name':'NO_SUCH_COUNTRY' }
        self.errorDesc[self.NO_SUCH_STANDARD] = { 'name':'NO_SUCH_STANDARD' }
        self.errorDesc[self.NO_SUCH_LESSON] = { 'name':'NO_SUCH_LESSON' }
        self.errorDesc[self.NO_SUCH_CONCEPT] = { 'name':'NO_SUCH_CONCEPT' }
        self.errorDesc[self.NO_SUCH_MEMBER] = { 'name':'NO_SUCH_MEMBER' }
        self.errorDesc[self.NO_SUCH_STATE] = { 'name':'NO_SUCH_STATE' }
        self.errorDesc[self.NO_SUCH_OVERLAY] = { 'name':'NO_SUCH_OVERLAY' }
        self.errorDesc[self.NO_SUCH_ANNOTATION] = { 'name':'NO_SUCH_ANNOTATION' }
        self.errorDesc[self.RETRIEVAL_ERROR] = { 'name':'RETRIEVAL_ERROR' }
        self.errorDesc[self.NO_SUCH_TASK] = { 'name':'NO_SUCH_TASK' }
        self.errorDesc[self.NO_SUCH_FEEDBACK] = { 'name':'NO_SUCH_FEEDBACK' }
        self.errorDesc[self.NO_SUCH_RESOURCE] = { 'name':'NO_SUCH_RESOURCE' }
        self.errorDesc[self.NO_SUCH_FAVORITE] = { 'name':'NO_SUCH_FAVORITE' }
        self.errorDesc[self.NO_SUCH_FEATURED_ARTIFACT] = { 'name':'NO_SUCH_FEATURED_ARTIFACT' }
        self.errorDesc[self.UNKNOWN_REALM_TYPE] = { 'name':'UNKNOWN_REALM_TYPE' }
        self.errorDesc[self.INVALID_VERSION] = { 'name':'INVALID_VERSION' }
        self.errorDesc[self.NO_SUCH_BROWSE_CANDIDATE] = { 'name':'NO_SUCH_BROWSE_CANDIDATE' }
        self.errorDesc[self.NO_SUCH_BROWSE_CATEGORY] = { 'name':'NO_SUCH_BROWSE_CATEGORY' }
        self.errorDesc[self.CANNOT_UPDATE_ARTIFACT] = { 'name':'CANNOT_UPDATE_ARTIFACT' }
        self.errorDesc[self.CANNOT_CREATE_EMBEDDED_OBJECT] = { 'name':'CANNOT_CREATE_EMBEDDED_OBJECT' }
        self.errorDesc[self.UNKNOWN_RESOURCE_TYPE] = { 'name':'UNKNOWN_RESOURCE_TYPE' }
        self.errorDesc[self.NO_SUCH_EMBEDDED_OBJECT] = { 'name':'NO_SUCH_EMBEDDED_OBJECT' }
        self.errorDesc[self.NO_SUCH_EMBEDDED_OBJECT_PROVIDER] = { 'name':'NO_SUCH_EMBEDDED_OBJECT_PROVIDER' }
        self.errorDesc[self.FORBIDDEN_EMBEDDED_OBJECT] = { 'name':'FORBIDDEN_EMBEDDED_OBJECT' }
        self.errorDesc[self.FORBIDDEN_RESOURCE] = { 'name': 'FORBIDDEN_RESOURCE' }
        self.errorDesc[self.NO_SUCH_ABUSE_REPORT] = { 'name':'NO_SUCH_ABUSE_REPORT' }
        self.errorDesc[self.NO_SUCH_APPROVAL_DOMAIN] = { 'name':'NO_SUCH_APPROVAL_DOMAIN' }
        self.errorDesc[self.VALIDATION_FAILED] = { 'name':'VALIDATION_FAILED' }
        self.errorDesc[self.NOT_AUTHORIZED_TO_PRINT] = {'name':'NOT_AUTHORIZED_TO_PRINT' }
        self.errorDesc[self.CANNOT_CREATE_WORKSHEET] = { 'name':' CANNOT CREATE WORKSHEET' }
        self.errorDesc[self.CANNOT_GET_DOWNLOADCOUNT] = { 'name':'CANNOT_GET_DOWNLOADCOUNT' }
        self.errorDesc[self.CANNOT_GET_DOWNLOADSTATSTYPES] = { 'name':'CANNOT_GET_DOWNLOADSTATSTYPES' }
        self.errorDesc[self.CANNOT_UPDATE_DOWNLOADSTATS] = { 'name':'CANNOT_UPDATE_DOWNLOADSTATS' }
        self.errorDesc[self.NO_SUCH_NOTIFICATION] = { 'name': 'NO_SUCH_NOTIFICATION' }
        self.errorDesc[self.NO_SUCH_LABEL] = { 'name': 'NO_SUCH_LABEL' }
        self.errorDesc[self.NO_SUCH_EVENT_TYPE] = { 'name': 'NO_SUCH_EVENT_TYPE' }
        self.errorDesc[self.NO_SUCH_GOOGLEDOC_AUTH] = { 'name': 'NO_SUCH_GOOGLEDOC_AUTH' }
        self.errorDesc[self.INVALID_HTML_CONTENT] = { 'name': 'INVALID_HTML_CONTENT' }
        self.errorDesc[self.NO_SUCH_NOTIFICATION_RULE] = { 'name': 'NO_SUCH_NOTIFICATION_RULE' }
        self.errorDesc[self.NO_SUCH_EVENT] = { 'name': 'NO_SUCH_EVENT' }
        self.errorDesc[self.NO_SUCH_SUBJECT] = { 'name': 'NO_SUCH_SUBJECT' }
        self.errorDesc[self.NO_SUCH_GRADE] = { 'name': 'NO_SUCH_GRADE' }
        self.errorDesc[self.NO_SUCH_STANDARD_BOARD] = { 'name': 'NO_SUCH_STANDARD_BOARD' }
        self.errorDesc[self.NO_SUCH_STANDARD_CORRELATION] = { 'name': 'NO_SUCH_STANDARD_CORRELATION' }
        self.errorDesc[self.CANNOT_CREATE_EVENT] = { 'name': 'CANNOT_CREATE_EVENT' }
        self.errorDesc[self.SUGGESTION_RETRIEVAL_ERROR] = { 'name': 'SUGGESTION_RETRIEVAL_ERROR' }
        self.errorDesc[self.NO_SUCH_VOCABULARY] = { 'name': 'NO_SUCH_VOCABULARY' }
        self.errorDesc[self.NO_SUCH_LANGUAGE] = { 'name': 'NO_SUCH_LANGUAGE' }
        self.errorDesc[self.NO_SUCH_OAUTH_CLIENT] = { 'name': 'NO_SUCH_OAUTH_CLIENT' }
        self.errorDesc[self.INVALID_EMAIL] = { 'name': 'INVALID_EMAIL' }
        self.errorDesc[self.MISSING_PASSWORD] = { 'name': 'MISSING_PASSWORD' }
        self.errorDesc[self.INVALID_LTI_CONSUMER_KEY] = { 'name': 'INVALID_LTI_CONSUMER_KEY' }
        self.errorDesc[self.CANNOT_CREATE_GROUP] = { 'name': 'CANNOT_CREATE_GROUP' }
        self.errorDesc[self.CANNOT_UPDATE_GROUP] = { 'name': 'CANNOT_UPDATE_GROUP' }
        self.errorDesc[self.CANNOT_DELETE_GROUP] = { 'name': 'CANNOT_DELETE_GROUP' }
        self.errorDesc[self.NO_SUCH_GROUP] = { 'name': 'NO_SUCH_GROUP' }
        self.errorDesc[self.CANNOT_ADD_MEMBER_TO_GROUP] = { 'name': 'CANNOT_ADD_MEMBER_TO_GROUP' }
        self.errorDesc[self.CANNOT_DELETE_MEMBER_FROM_GROUP] = { 'name': 'CANNOT_DELETE_MEMBER_FROM_GROUP' }
        self.errorDesc[self.UNABLE_TO_GET_MEMBERS] = { 'name': 'UNABLE_TO_GET_MEMBERS' }
        self.errorDesc[self.CANNOT_ACTIVATE_GROUP_MEMBER] = { 'name': 'CANNOT_ACTIVATE_GROUP_MEMBER' }
        self.errorDesc[self.CANNOT_DECLINE_GROUP_MEMBER] = { 'name': 'CANNOT_DECLINE_GROUP_MEMBER' }
        self.errorDesc[self.GROUP_ALREADY_EXISTS] = { 'name': 'GROUP_ALREADY_EXISTS' }
        self.errorDesc[self.MEMBER_ALREADY_EXISTS] = { 'name': 'MEMBER_ALREADY_EXISTS' }
        self.errorDesc[self.MEMBER_ROLE_CONFLICT] = { 'name': 'MEMBER_ROLE_CONFLICT' }
        self.errorDesc[self.MEMBER_ALREADY_ASSOCIATED] = { 'name': 'MEMBER_ALREADY_ASSOCIATED' }
        self.errorDesc[self.GENERIC_ERROR] = { 'name': 'GENERIC_ERROR' }

    def asDict(self, errorCode, message=None, infoDict=None):
        errDict = {
                    'responseHeader':{'status':errorCode, 'QTime':0},
                    'response':{
                    },
                  }
        if message is not None:
            errDict['response']['message'] = message
        if infoDict is not None:
            errDict['response'].update(infoDict)
        return errDict

    def getName(self, id):
        errorCode = int(id)
        if self.errorDesc.has_key(errorCode):
            errorDesc = self.errorDesc[errorCode]
            name = errorDesc['name']
        else:
            name = 'UNKNOWN ERROR'
        return name

    def getDescription(self, id):
        errorCode = int(id)
        if self.errorDesc.has_key(errorCode):
            errorDesc = self.errorDesc[errorCode]
            name = errorDesc['name']
            desc = u'The description of error %s' % name
        else:
            name = 'UNKNOWN ERROR'
            desc = 'Unknow error code %d' % id
        return name, desc
