	<form class="createquestionform algorithmicquestionform">
		<h4>{{ _("Write down the variable rules") }} <span class="helppanel" id="alg-inputrules-help" ><span class="ex-help-icon"></span></span></h4>
		<div class="ui-corner-all input_rules exerciseinput">
                        <div class="field-title">
                                {{ _('Available variables') }}
                        </div>
                        <div id="generative_variables"><p><em>There are no variables currently available.</em></p></div>
		
			<div class="addrulesblock">
                                <span class="addremoverule addvariable" title="{{ _('add new rule box') }}">Add Variable</span>
				<span class="errorspan er_rules"></span>
			</div>
		</div>
		<span id="er_variables" class="errorspan"></span>

		<h4>{{ _('Write down your question text (enclose variable names between $$, e.g. $variables$)') }} <span class="helppanel" id="alg-question-help" ><span class="ex-help-icon"></span></span></h4>
		<div class="input_question">
			<textarea class="ui-corner-all questiontext exerciseinput forminput" name="generativeQuestion" value="" ></textarea>
			<div class="clear">
			</div>
			<span class="errorspan" id="er_invalid_question"></span>
		</div>

		<!-- For 02/21 we are only supporting multiple choice questions -->
		<!--
		<h4>{{ _('Choose a question format') }} <span class="helppanel" id="gen-distractors-help" ><span class="ex-help-icon"></span></span></h4>
		<div class="input_questiontype">
			<div class="questiontypebox selected" id="multichoicetype">
				<div class="qtype_choosebtn" title="{{ _('Choose Multichoice Answer') }}">
				</div>
				<div class="qtype_display">
					<label>{{ _('Multiple-Choice Question') }}</label>
				</div>
			</div>
			<div class="questiontypebox" id="truefalsetype">
				<div class="qtype_choosebtn" title="{{ _('Choose True/False Answer') }}">
				</div>
				<div class="qtype_display">
					<label>{{ _('True/False Question') }}</label>
				</div>
			</div>
		</div>-->
		<div class="clear"></div>
		
		<h4>{{ _('Enter the options') }}</h4>
		<div class="ui-corner-all input_distractors exerciseinput">
			<div class="multiplechoicedistractors distractorsblock currentblock">
				<div class="field-title">
					{{ _('Enter the answer expression for options') }}
				</div>
                                <table>
                                        <tr id="distractor1">
                                                <td class="optionlabel">
							<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
								<span class="optionno">1</span>
							</div>
                                                </td>
                                                <td class="optionfields hide">
                                                        <input type="text" class="forminput distractor_eq" name="distractorAlgebraicText_multiple_1" placeholder="{{ _('Python code') }}"></>
                                                </td>
                                                <td class="optionfields">
                                                        <input type="text" class="forminput distractor_text" name="distractorDisplayText_multiple_1" placeholder="{{ _('Answer Expression') }}"></>
                                                </td>
                                        </tr>
                                        </tr>   <td></td> <td></td> <td></td> </tr>
                                        <tr id="distractor2">
                                                <td class="optionlabel">
							<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
								<span class="optionno">2</span>
							</div>
                                                </td>
                                                <td class="optionfields hide">
                                                        <input type="text" class="forminput distractor_eq" name="distractorAlgebraicText_multiple_2" placeholder="{{ _('Python code') }}"></>
                                                </td>
                                                <td class="optionfields">
                                                        <input type="text" class="forminput distractor_text" name="distractorDisplayText_multiple_2" placeholder="{{ _('Answer Expression') }}"></>
                                                </td>
                                        </tr>
                                        </tr>   <td></td> <td></td> <td></td> </tr>
                                        <tr id="distractor3">
                                                <td class="optionlabel">
							<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
								<span class="optionno">3</span>
							</div>
                                                </td>
                                                <td class="optionfields hide">
                                                        <input type="text" class="forminput distractor_eq" name="distractorAlgebraicText_multiple_3" placeholder="{{ _('Python code') }}"></>
                                                </td>
                                                <td class="optionfields">
                                                        <input type="text" class="forminput distractor_text" name="distractorDisplayText_multiple_3" placeholder="{{ _('Answer Expression') }}"></>
                                                </td>
                                        </tr>
                                        </tr>   <td></td> <td></td> <td></td> </tr>
                                        <tr id="distractor4">
                                                <td class="optionlabel">
							<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
								<span class="optionno">4</span>
							</div>
                                                </td>
                                                <td class="optionfields hide">
                                                        <input type="text" class="forminput distractor_eq" name="distractorAlgebraicText_multiple_4" placeholder="{{ _('Python code') }}"></>
                                                </td>
                                                <td class="optionfields">
                                                        <input type="text" class="forminput distractor_text" name="distractorDisplayText_multiple_4" placeholder="{{ _('Answer Expression') }}"></>
                                                </td>
                                        </tr>
                                        </tr>   <td></td> <td></td> <td></td> </tr>
                                </table>
                                <span class="errorspan er_hasnotick"></span>
                                <span class="errorspan er_noduplicateoption"></span>
				<!--

				<ul class="distractorbox" id="field_titles">
					<li>
					<span class="disttitle">{{ _('Correct ?') }}</span>
					</li>
					<li>
					<span class="disttitle hide">{{ _('Answer Expression') }}</span>
					</li>
					<li>
					<span class="disttitle">{{ _('Option Text') }}</span>
					</li>
				</ul>
				<ul class="distractorbox optionbox multiplechoiceoptions" id="distractor1">
					<li>
					<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
						<span class="optionno">1</span>
					</div>
					</li>

					<li>
					<div class="question_dist_eq hide">
						<input type="text" class="forminput distractorAlgebraicText" name="distractorAlgebraicText_multiple_1" placeholder="{{ _('Python code') }}"></>
					</div>
					</li>
					<li>
					<div class="question_dist_text">
						<input type="text" class="forminput" name="distractorDisplayText_multiple_1" placeholder="{{ _('text with $variables$') }}"></>
					</div>
					</li>
				</ul>
				<ul class="distractorbox optionbox multiplechoiceoptions" id="distractor2">
					<li>
					<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
						<span class="optionno">2</span>
					</div>
					</li>

					<li>
					<div class="question_dist_eq hide">
						<input type="text" class="forminput distractorAlgebraicText" name="distractorAlgebraicText_multiple_2" placeholder="{{ _('Python code') }}"></>
					</div>
					</li>
					<li>
					<div class="question_dist_text">
						<input type="text" class="forminput" name="distractorDisplayText_multiple_2" placeholder="{{ _('text with $variables$') }}"></>
					</div>
					</li>
				</ul>
				<ul class="distractorbox optionbox multiplechoiceoptions" id="distractor3">
					<li>
					<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
						<span class="optionno">3</span>
					</div>
					</li>

					<li>
					<div class="question_dist_eq hide">
						<input type="text" class="forminput distractorAlgebraicText" name="distractorAlgebraicText_multiple_3" placeholder="{{ _('Python code') }}"></>
					</div>
					</li>
					<li>
					<div class="question_dist_text">
						<input type="text" class="forminput" name="distractorDisplayText_multiple_3" placeholder="{{ _('text with $variables$') }}"></>
					</div>
					</li>
				</ul>
				<ul class="distractorbox optionbox multiplechoiceoptions" id="distractor4">
					<li>
					<div class="iscorrect_checkbox " title="{{ _('Tick Correct Option') }}">
						<span class="optionno">4</span>
					</div>
					</li>

					<li>
					<div class="question_dist_eq hide">
						<input type="text" class="forminput distractorAlgebraicText" name="distractorAlgebraicText_multiple_4" placeholder="{{ _('Python code') }}"></>
					</div>
					</li>
					<li>
					<div class="question_dist_text">
						<input type="text" class="forminput" name="distractorDisplayText_multiple_4" placeholder="{{ _('text with $variables$') }}"></>
					</div>
					</li>
				</ul>
				-->
			</div>
<!--			<div class="truefalsedistractors distractorsblock">
				<div class="field-title">
					{{ _('Mark whether your question is true or false') }}
				</div>
				<div class="optionbox" id="option1">
					<div class="iscorrect_checkbox " title="{{ _('Tick True') }}">
					</div>
					<div class="question_option">
						<input type="text" class="forminput" name="declarativeOption_truefalse_1" value="True" readonly="readonly"></>
					</div>
				</div>
				<div class="optionbox" id="option2">
					<div class="iscorrect_checkbox " title="{{ _('Tick False') }}">
					</div>
					<div class="question_option">
						<input type="text" class="forminput" name="declarativeOption_truefalse_2" value="False" readonly="readonly"></>
					</div>
				</div>
				<span class="errorspan"></span>
			</div>
			-->
		</div>
		<h4>{{ _('Choose difficulty level') }}</h4>
		<div class="input_difficultylevel">
			<div class="difficultylevelbox" id="easy">
				<div class="difficulty_choosebtn" title="{{ _('Easier than typical') }}">
				</div>
				<div class="difficulty_display">
					<label>{{ _('Easy') }}</label>
				</div>
			</div>
			<div class="difficultylevelbox selected" id="normal">
				<div class="difficulty_choosebtn" title="{{ _('Normal difficulty level') }}">
				</div>
				<div class="difficulty_display">
					<label>{{ _('Normal') }}</label>
				</div>
			</div>
			<div class="difficultylevelbox" id="hard">
				<div class="difficulty_choosebtn" title="{{ _('Harder than typical') }}">
				</div>
				<div class="difficulty_display">
					<label>{{ _('Hard') }}</label>
				</div>
			</div>
		</div>
		<div class="clear">
		</div>
	</form>
	
	<div class="hide">
        	<div id="js_dialog_variable_editor">
                        <div class="var_dialog_header">
                                {{ _('Variable Editor')}}
                        </div>
                        <div class="var_dialog_body">
                                <div class="variable_name">
                                    <label class="var_dialog_label">{{ _('Variable Name') }}</label>
                                    <input type="text" class="modal_forminput" name="variable_name_input" placeholder="{{ _('Enter variable name') }}"></input>
                                    <span class="var_dialog_error hide" id="var_dialog_name_error"></span>
                                </div>
                                <div class="clear"></div>
                                <div class="var_type">
                                        <span class="var_dialog_label">Choose a variable type</span>
                                        <ul class="var_type_selector">
                                        <li>
                                        	<span><input type="radio" class="var_type_radio" checked="true" name="var_type" value="constant"></input></span>
                                        	<span>Constant</span>
                                        </li>
                                        <li>
                                        	<span><input type="radio" class="var_type_radio" name="var_type" value="random"></input></span>
                                        	<span>Random</span>
                                        </li>
                                        <li>
                                        	<span><input type="radio" class="var_type_radio" name="var_type" value="rule"></input></span>
                                        	<span>Rule based</span>
                                        </li>
                                        </ul>
                                </div>
                                <div class="clear"></div>
                                <div class="var_edit_pane" id="variable_constant_pane">
                                    <div class="variable_value var_row">
                                        <label class="var_dialog_label">{{ _('Constant Value') }}</label>
                                        <input type="text" class="modal_forminput" name="variable_value_input" placeholder="{{ _('Enter variable value') }}"></input>
                                        <span class="var_dialog_error hide" id="var_dialog_constant_error"></span>
                                    </div>
                                </div>
                                <div class="var_edit_pane hide" id="variable_random_pane">
                                    <label class="var_dialog_instruction var_dialog_label">{{ _('Choose a value') }}</label>
                                    <ul class="var_type_selector">
                                        <li>
                                            <span><input type="radio" class="var_random_type_radio" checked="true" name="random_type" value="list"></input></span>
                                            <span>List</span>
                                        </li>
                                        <li>
                                            <span><input type="radio" class="var_random_type_radio" name="random_type" value="range"></input></span>
                                            <span>Range</span>
                                        </li>
                                    </ul>
                                    <div class="var_random_builder">
                                        <div class="var_random_builder_pane var_row" id="random_list_pane">
                                        	<label class="var_dialog_label">{{ _('From the following list (comma separated values)') }}</label>
                                        	<input type="text" class="modal_forminput" name="variable_list_input" placeholder="{{ _('Enter comma separated values') }}"></input>
                                        	<span class="var_dialog_error hide" id="var_dialog_random_list_error"></span>
                                        </div>
                                        <div class="var_random_builder_pane hide"  id="random_range_pane">
                                        	<div class="random_range_row var_row">
                                        	<label class="var_dialog_label">{{ _('Starting from (inclusive)') }}</label>
                                        	<input type="text" class="modal_forminput" name="variable_from_input" placeholder="{{ _('Enter starting value') }}"></input>
                                        	<span class="var_dialog_error hide" id="var_dialog_random_from_error"></span>
                                        	</div>
                                        	<div class="clear"></div>
                                        	
                                        	<div class="random_range_row var_row">
                                        	<label class="var_dialog_label">{{ _('To (inclusive)') }}</label>
                                        	<input type="text" class="modal_forminput" name="variable_to_input" placeholder="{{ _('Enter ending value') }}"></input>
                                        	<span class="var_dialog_error hide" id="var_dialog_random_to_error"></span>
                                        	</div>
                                        	<div class="clear"></div>
 
                                        	<div class="random_range_row var_row">
                                        	<label class="var_dialog_label">{{ _('With interval') }}</label>
                                        	<input type="text" class="modal_forminput" name="variable_interval_input" value="1"></input>
                                        	<span class="var_dialog_error hide" id="var_dialog_random_interval_error"></span>
                                        	</div>
                                        	<div class="clear"></div>

                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="var_edit_pane hide" id="variable_rule_pane">
                                    <div class="var_row">
                                    <label class="var_dialog_label">{{ _('Enter rule ') }}</label>
                                    <input type="text" class="modal_forminput" name="var_rule" placeholder="{{ _('Enter rule') }}"></input>
                                    <span class="var_dialog_error hide" id="var_dialog_rule_error"></span>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="var_separator"></div>
                                <div class="var_submitbtn btn secondary">Create</div>
                                <div class="clear"></div>
                                <div class="hide" id="var_dialog_storage">
                                        <input type="hidden" name="var_dialog_mode" value="create"></input>
                                        <input type="hidden" name="var_edited" value=""></input>
                                </div>
                        </div>
		</div>
	</div>
